<html>
<head>
	<title><?php>echo $this->title ?></title>
</head>
<body>
	<h1><?php echo $this->title;?></h1>
    <!--  <?php foreach ($this->arr1 as $key => $value) {?>
           <?php echo $value.'<br>';?>
     <?php }?>
     <?php foreach ($this->list as $key => $value) {?>
           <?php echo $value['id'].'<br>'.$value['content'].'<br>'.$value['ctime'].'<br>';?>
     <?php }?> -->
     <form action='uplade' method='post' enctype="multipart/form-data" id ='from_1'>
     	<input type='text' name='content'/>
     	<input type='file' name='upload'/>
     	<input type='submit' value='submit'>  
     </form>
<script>
$(document).on('submit','#from_1',function(){
	var coo = $('input[name="content"]').val();
	if(coo == '')
	{
		alert(123);
		return false;
	}
});
	
</script>
</body>
</html>