<script src="/js/thumbnails.js" type="text/javascript"></script>
<nav class="col-md-2 hidden-print dev-sidebar">
    <?php include(dirname(__FILE__) . '/../sys/dev_nav.phtml')?>
</nav>
<style>
.s{color:red;}
th {text-align: center;}
</style>

<div class="col-md-10">
    <ol class="breadcrumb">
      <li><a href="warehouselist">经销商管理</a></li>
      <li class="active">详情信息</li>
    </ol>
    <ul class="nav nav-pills">
      <li role="presentation"><a href="warehouselist">经销商列表</a></li>
	  <li role="presentation" class="active"><a href="javascript:void(0)">详情信息</a></li>
    </ul>
    <br>
    <?php
      if ($this->errors != '') {
        echo "<div class='alert alert-danger alert-dismissible' role='alert'>
          <button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
      <strong>{$this->errors}</strong>
        </div>";
      }
    ?><br>
    <div class="tab-content">
    <fieldset disabled>
            <input type='hidden' name='id' value='<?=$this->info['id']?>'>
            <div class="form-group col-sm-12">
                <label class="col-sm-2 control-label">公司</label>
                <div class="col-sm-3">
                    <select name="status" class="form-control">
                        <?php foreach ($this->getCompanyList as $k => $v): ?>
                        	<option value="<?=$v['id']?>" <?=($this->info['company_id']==$v['id'])?'selected="selected"':'';?> ><?=$v['name']?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            <div class="form-group col-sm-12">
        		<label class="col-sm-2 control-label" for="Bingtuan_goodsName">经销商名称</label>
                <div class="col-sm-3">
        			<input type="text" class="form-control" name='warehousename' value='<?=$this->info['warehousename']?>'><span></span>
                </div>
            </div>
            <div class="form-group col-sm-12">
                <label class="col-sm-2 control-label">联系人</label>
                <div class="col-sm-3">
                  <input type="text" class="form-control" name='contact' value='<?=$this->info['contact']?>'>
                </div>
            </div>
            <div class="form-group col-sm-12">
                <label class="col-sm-2 control-label">联系人手机</label>
                <div class="col-sm-3">
                  <input type="text" class="form-control" name='mobile' value='<?=$this->info['mobile']?>'>
                </div>
            </div>
            <div class="form-group col-sm-12">
                <label class="col-sm-2 control-label">描述</label>
                <div class="col-sm-5">
                  <textarea class="form-control" name='describe' rows="4" cols='4'><?=$this->info['describe']?></textarea>
                </div>
            </div>
            <div class="form-group col-sm-12">
                <label class="col-sm-2 control-label">运营状态</label>
                <div class="col-md-3">
                    <select name="status" class="form-control">
                        <option value="1" <?=($this->info['status']==1)?'selected="selected"':'';?> >运营中</option>
                        <option value="0" <?=($this->info['status']==0)?'selected="selected"':'';?>>暂停运营</option>
                    </select>
                </div>
            </div>
            <div class="form-group col-sm-12">
                <label class="col-sm-2 control-label">录入时间</label>
                <div class="col-sm-5">
                  <?=date('Y-m-d H:i:s', $this->info['create_time'])?>
                </div>
            </div>
            <div class="form-group col-sm-12">
                <label class="col-sm-2 control-label">二维码</label>
                <div class="col-md-3">
                    <a href='<?=$this->info['codeImg']?>' target='_blank'>
                        <img src="<?=$this->info['codeImg']?>" alt="加载中..." class="img-rounded" width='200px' height='200px'>
                    </a>
                </div>
            </div>
        </fieldset>
    </div>
</div>
