<script src="/js/thumbnails.js" type="text/javascript"></script>
<nav class="col-md-2 hidden-print dev-sidebar">
    <?php include(dirname(__FILE__) . '/../sys/dev_nav.phtml')?>
</nav>
<style>
.current{color:#000000;}
th {text-align: center;}
</style>

<div class="col-md-10">
    <ol class="breadcrumb">
      <li><a href="javascript:void(0)">角色管理</a></li>
      <li class="active">角色列表</li>
    </ol>
    <ul class="nav nav-pills">
      <li role="presentation" class="active"><a href="#">角色列表</a></li>
      <?php if ($this->rbac == '*' ? true : false) :?>
        <li role="presentation"><a href="roleadd">添加角色</a></li>
      <?php endif; ?>
    </ul>
    <br>
    <div id="modal" class='col-md-12'></div>
    <br>
    <div class="table-wrapper products-table section mt-20">
        <div class="row">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th class="col-xs-2">ID</th>
                    <th class="col-md-4">角色名</th>
                    <th class="col-md-1">操作</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($this->roleList as $key=>$val) { ?>
                    <tr id="role_<?= $val['id']; ?>">
                        <td class='text-center col-xs-4'><?= $val['id'] ?></td>
                        <td class='text-center col-xs-4'><?=$val['name'] ?></td>
                        <td class='text-center col-xs-4'>
                            <ul class="list-inline">
                                <?php if ($this->rbac == '*' ? true : false) :?>
                                    <li><a href="/developer/roleupdate?id=<?= $val['id']; ?>">编辑</a></li>
                                <?php else: ?>
                                    <li>无权限操作</li>
                                <?php endif; ?>
                                <?php if ($this->rbac == '*' ? true : false) :?>
                                    <li class="last"><a onclick="if(confirm('您确定要删除该角色吗？')==false)return false; del(<?=$val['id']?>,1)">删除</a></li>
                                <?php endif; ?>
                            </ul>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
        <?=$this->paglist?>
    </div>
</div>

<script type="text/javascript">
function del(id)
{
    $.ajax({
     type: "POST",
     url: "roledelete",
     dataType: "json",
     data: "id="+id,
     success: function(data){
       if (data == 200) {
         $("#role_"+id).remove();
         $("#modal").append('<div class="alert alert-success alert-roledelete-'+id+'" role="alert"><p>删除成功</p></div>');
         setTimeout(function(){$(".alert-roledelete-"+id).remove()},2000);
       }
       if (data == 400) {
         alert('请重试');
       }
     }
  });
}
</script>