<div class="col-md-4">
</div>
<div class="col-md-4 div-single">
  <?php if ($this->error): ?>
  <div class="alert alert-warning" role="alert"><?=$this->error?></div>
  <?php endif; ?>

  <form class="form-signin" method="POST">
<!--       <label for="inputEmail" class="sr-only">Email address</label> -->
      <input type="text" name="username" id="inputEmail" class="form-control" placeholder="账号" required autofocus>
<!--       <label for="inputPassword" class="sr-only">Password</label> -->
      <input type="password" name="password" id="inputPassword" class="form-control" placeholder="密码" required>
      <button class="btn btn-md btn-primary btn-block" type="submit">登 录</button>
  </form>  
</div>

<style>
.form-signin input, .form-signin button {margin: 10px 0;}
.div-signin-tips {text-align: center; margin-top:30px; color: #666666}
.div-signin-tips a {color: #666; text-decoration: none}
.div-signin-tips a:hover {color: red; text-decoration: underline;}
</style>