<script src="/js/thumbnails.js" type="text/javascript"></script>
<nav class="col-md-2 hidden-print dev-sidebar">
    <?php include(dirname(__FILE__) . '/../sys/dev_nav.phtml')?>
</nav>
<div class="col-md-10">
    <ol class="breadcrumb">
      <li><a href="/developer/rbclist">应用列表</a></li>
      <li class="active">编辑应用</li>
    </ol>
    <ul class="nav nav-pills">
        <li role="presentation"><a href="/developer/rbclist">应用列表</a></li>
        <li role="presentation"  class="active"><a href="javascript:void(0)">编辑应用</a></li>
    </ul>
    <br>
    <hr>
    <?php if ($this->error): ?>
    <div class="alert alert-warning" role="alert"><?=$this->error?></div>
    <?php endif; ?>
    <div class="tab-content">
        <form action='' method="POST"  class="form-horizontal col-sm-12">
            <div class="form-group col-sm-12">
                <label class="col-sm-2 control-label">名称<span class='s'> *</span></label>
                <div class="col-sm-5">
                    <input type="text" name="name" class='form-control' placeholder="请输入应用名称" value="<?php echo $this->menuinfo['name']; ?>">
                </div>
            </div>
            <div class="form-group col-sm-12">
                <label class="col-sm-2 control-label" for="Bingtuan_goodsName">控制器<span class='s'> *</span></label>
                <div class="col-sm-5">
                    <input type="text" name="controller" class='form-control' placeholder="请输入控制器名称" value="<?php echo $this->menuinfo['controller']; ?>">
                </div>
            </div>
            <div class="form-group col-sm-12">
                <label class="col-sm-2 control-label">模块<span class='s'> *</span></label>
                <div class="col-sm-5">
                    <input type="text" name="method" class='form-control' placeholder="请输入模块名称" value="<?php echo $this->menuinfo['method']; ?>">
                </div>
            </div>
            <div class="form-group col-sm-12">
                <div class="col-sm-offset-2 col-sm-10">
                    <input type="hidden" name="id" value="<?php echo $this->menuinfo['id']; ?>">
                  <button type="submit" class="btn btn-success">提交</button>
                </div>
            </div>
        </form>
    </div>
 </div>
 <style>
 .s{color:red;}
.form-updatepwd input, .form-updatepwd button {margin: 10px 0; width: 200px;}
</style>