<nav class="col-md-2 hidden-print dev-sidebar">
    <?php include(dirname(__FILE__) . '/../sys/dev_nav.phtml')?>
</nav>
<style>
.current{color:#000000;}
th {text-align: center;}
</style>

 <div class="col-md-10">
    <ol class="breadcrumb">
      <li><a href="/addressOffice/addressOfficeList">分公司列表</a></li>
      <li class="active">账号列表</li>
    </ol>
    <ul class="nav nav-pills">
      <li role="presentation"><a href="/addressOffice/addressOfficeList">分公司列表</a></li>
      <li role="presentation" class="active"><a>账号列表</a></li>
	  <li role="presentation"><a href="/developer/zone?id=<?= $this->ID ?>">添加账号</a></li>
    </ul>
    <br>
    <div class="table-wrapper products-table section mt-20 mr-10" >
        <div class="row">
           <table class="table table-hover" style="text-align: center;">
                <caption></caption>
                <thead>
                    <tr>
                      <th>ID</th>
                      <th>名称</th>
            		  <th>生成时间</th>
                      <th>操作</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if ($this->adm): ?>
                        <?php foreach ($this->adm as $adm): ?>
                            <tr id='is_del_<?=$adm['id']?>'>
                              <td class='col-xs-1'><?=$adm['id']?></td>
                              <td class='col-xs-1'><?=$adm['name']?></td>
                              <td class='col-xs-2'><?=date('Y-m-d H:i',$adm['create_time'])?></td>
                              <td class='col-xs-3'>
                                <a href="roleupdate?id=<?=$adm['id']?>"><span class="glyphicon glyphicon-pencil"></span> 设置权限</a>
                                <a href="update?id=<?=$adm['id']?>"><span class="glyphicon glyphicon-pencil"></span> 编辑</a>
                                <a href="javascript:void(0)" onclick="if(confirm('操作不可恢复，确认删除么？')==false)return false;del(<?=$adm['id']?>)"><span class="glyphicon glyphicon-trash"></span> 删除</a>
                              </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
            <?php echo $this->paglist; ?>
        </div>
    </div> 
</div>

<script>
function del(id)
{
    $.ajax({
 	   type: "POST",
 	   url: "delete",
 	   dataType: "json",
 	   data: "id="+id,
 	   success: function(data){
 		   if (data == 200) {
 			   $("#is_del_"+id).remove();
 			   $("#modal").append('<div class="col-md-3"></div><div class="col-md-6" style="margin-top: 60px"><div class="alert alert-success" role="alert"><p>删除成功</p></div></div><div class="col-md-3"></div>');
 			   setTimeout(function(){$("#modal").modal("hide")},2000);
 		   }
 		   if (data == 400) {
 			   alert('请重试');
 		   }
 	   }
 	});
}
</script>