<script src="/js/thumbnails.js" type="text/javascript"></script>
<nav class="col-md-2 hidden-print dev-sidebar">
    <?php include(dirname(__FILE__) . '/../sys/dev_nav.phtml')?>
</nav>

<div class="col-md-10">
    <ol class="breadcrumb">
      <li><a href="/addressOffice/addressOfficeList">分公司列表</a></li>
      <li class="active">添加账号</li>
    </ol>
    <ul class="nav nav-pills">
      <li role="presentation"><a href="/addressOffice/addressOfficeList">分公司列表</a></li>
      <li role="presentation"><a href='/developer/zonelist?id=<?= $this->ID ?>'>分公司账号列表</a></li>
	  <li role="presentation" class="active"><a>添加分公司账号</a></li>
    </ul>
    <br>
    <?php
      if ($this->errors != '') {
        echo "<div class='alert alert-danger alert-dismissible' role='alert'>
          <button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
      <strong>{$this->errors}</strong>
        </div>";
      }
    ?>
    <br>
    <br>
    <div class="tab-content col-xs-12">
      <form action="/developer/zone" method="post" accept-charset="utf-8" class="form-horizontal">
        <div class="form-group">
            <label class="col-sm-2 control-label">名称<i class="s">*</i></label>
            <div class="col-sm-5">
                <input type="text" name="name" class="form-control" value="<?= $this->user['name'] ?>" placeholder="账号名称">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">公司<span class="s">(权限组)</span> <i class="s">*</i></label>
            <div class="col-sm-5">
                <select class='form-control col-xs-4'>
                    <option value=''>请选择</option>
                    <?php if ($this->companyList): ?>
                        <?php foreach ($this->companyList as $k => $v): ?>
                            <option value='<?=$v['id']?>'><?=$v['companyname']?></option>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">登录账号<i class="s">*</i></label>
            <div class="col-sm-5">
                <input type="text" name="username" class="form-control" value="<?= $this->user['username'] ?>" placeholder="账号登录账号">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">密码<i class="s">*</i></label>
            <div class="col-sm-5">
                <input type="password" name="pwd" class="form-control" value="<?= $this->user['pwd'] ?>" placeholder="请输入密码">
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">确认密码<i class="s">*</i></label>
            <div class="col-sm-5">
                <input type="password" name="confirm" class="form-control" value="<?= $this->user['confirm'] ?>" placeholder="再次输入密码">
            </div>
        </div>
        <hr class="clearfix">
        <div class="form-group">
            <label class="col-sm-2 control-label"></label>
            <div class="col-sm-10">
                <button type="submit" class="btn btn-success">提交</button>    
            </div>
        </div>
    </form>
    </div>
</div>

<style>
.s{color:red;}
.form-signin input, .form-signin button {margin: 10px 0;}
</style>