    <!-- libraries -->
    <link href="<?php echo $this->cdnUrl . '/css/lib/uniform.default.css'; ?>" type="text/css" rel="stylesheet">
    <link href="<?php echo $this->cdnUrl . '/css/lib/select2.css'; ?>" type="text/css" rel="stylesheet">
    <link href="<?php echo $this->cdnUrl . '/css/lib/bootstrap.datepicker.css'; ?>" type="text/css" rel="stylesheet">
    <link href="<?php echo $this->cdnUrl . '/css/lib/font-awesome.css'; ?>" type="text/css" rel="stylesheet" >

    <!-- global styles -->
    <link rel="stylesheet" type="text/css" href="<?php echo $this->cdnUrl . '/css/compiled/layout.css'; ?>">
    <link rel="stylesheet" type="text/css" href="<?php echo $this->cdnUrl . '/css/compiled/elements.css'; ?>">

    <link rel="stylesheet" type="text/css" href="<?php echo $this->cdnUrl . '/css/compiled/icons.css'; ?>">
    <link rel="stylesheet" type="text/css" href="<?php echo $this->cdnUrl . '/css/compiled/tables.css'; ?>">
    <!-- this page specific styles -->
    <link rel="stylesheet" href="<?php echo $this->cdnUrl . '/css/compiled/form-showcase.css'; ?>" type="text/css" media="screen" >
    <!-- open sans font -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href="<?php echo $this->cdnUrl . '/css/bootstrap/bootstrap.css';?> " rel="stylesheet">
    <link href="<?php echo $this->cdnUrl . '/img/log/bing.jpg'; ?>" rel="shortcut icon" type="image/vnd.microsoft.icon">
    <link href="<?php echo $this->cdnUrl . '/css/bootstrap/bootstrap-overrides.css'; ?>" rel="stylesheet">

    <link href="<?php echo $this->cdnUrl . '/css/public.css'; ?>" rel="stylesheet">