<script type="text/javascript" src="<?= $this->cdnUrl; ?>/js/bootstrap.datepicker.js"></script>
<script type="text/javascript" src="<?= $this->cdnUrl; ?>/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?= $this->cdnUrl; ?>/js/jquery.uniform.min.js"></script>
<script type="text/javascript" src="<?= $this->cdnUrl; ?>/js/select2.min.js"></script>
<script type="text/javascript" src="<?= $this->cdnUrl; ?>/js/hhjslib.min.js"></script>
<script type="text/javascript" src="<?php echo $this->cdnUrl . '/upload/js/jquery.uploadify.js'; ?>"></script>
<script type="text/javascript" src="<?php echo $this->cdnUrl . '/js/amd/hjz-extend.js'; ?>"></script>
<script type="text/javascript" src="<?php echo $this->cdnUrl . '/js/amd/common.js'; ?>"></script>
