<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>冰团网</title>   
    <!-- bootstrap -->
    <link href="/css/bootstrap/bootstrap.css" rel="stylesheet">
    <!-- libraries -->
    <link href="/css/lib/font-awesome.css" type="text/css" rel="stylesheet" >

    <!-- global styles -->
    <link href="/css/lib/bootstrap.datepicker.css" type="text/css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/css/compiled/layout.css">
    <link rel="stylesheet" type="text/css" href="/css/compiled/elements.css">
    <link rel="stylesheet" type="text/css" href="/css/compiled/tables.css">
    <!-- this page specific styles -->
    <link rel="stylesheet" href="/css/compiled/form-showcase.css" type="text/css" media="screen" >
    <!-- open sans font -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" href="/css/public.css">