<nav class="col-md-2 hidden-print dev-sidebar">
    <?php include(dirname(__FILE__) . '/../sys/dev_nav.phtml')?>
</nav>
<script src="/js/thumbnails.js" type="text/javascript"></script>
<script src="/laydate/laydate.js" type="text/javascript"></script>
<script>
    laydate.skin('danlan')
</script>
<style>
th {text-align: center;}
td>div{width:29%;float:left;padding:0.3em}
td>input{width:12%;}
.current{color:red;}
</style>
<div class="col-md-10">
    <ol class="breadcrumb">
      <li><a href="#">公司账单管理</a></li>
      <li class="active">公司账单列表</li>
    </ol>
    <form action="" id='ajaxform' method="get">
        <table class="table" style="background:#f5f5f5">
            <tr>
                <td>
                    <div class='input-group col-md-5' style='float: left'>
                        <div class="input-group">
                            <div class="input-group-addon">时间</div>
                            <input class='form-control' style='width:50%;display: inline' type="text" placeholder="开始时间" onclick="laydate()" name="ktime" id='ktime' value='<?=$this->get['ktime']?>'>
                            <input class='form-control' style='width:50%;display: inline' name="gtime" id='gtime' type="text" placeholder="结束时间" onclick="laydate()" value='<?=$this->get['gtime']?>'>
                        </div>
                    </div>
<!--                     <div class='input-group col-md-5' style='float: left'>
                        <div class="input-group">
                            <div class="input-group-addon">价格</div>
                            <input class='form-control' style='width:50%;display: inline' type="text" placeholder="下限-价格" name="minprice" value='<?=$this->get['minprice']?>'>
                            <input class='form-control' style='width:50%;display: inline' type="text" placeholder="上限-价格" name="maxprice" value='<?=$this->get['maxprice']?>'>
                        </div>
                    </div> -->
                    <div class="input-group col-sm-3" style='float: left'>
                        <div class="input-group-addon">公司</div>
                        <select name="company_id" class="form-control">
                            <option value='0'>全部</option>
                            <?php foreach ($this->getCompanyList as $k => $v): ?>
                            	<option value="<?=$v['id']?>" <?=($this->get['company_id']==$v['id'])?'selected="selected"':'';?> ><?=$v['name']?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <span style='float:right;padding:0.3em'>
                        <input class="btn btn-primary" type="submit" value="搜索">
                    </span>
                </td>
            </tr>
                
        </table>
    </form>
    <table class="table table-hover" style="text-align: center;">
    <caption></caption>
    <thead>
        <tr>
            <th>分公司名称</th>
            <th>订单数</th>
            <th>金额</th>
            <th>结算状态</th>
            <th>结算时间</th>
            <th>操作</th>
        </tr>
    </thead>
      <tbody>
        <?php if ($this->list): ?>
        <?php foreach ($this->list as $info): ?>
            <tr id='is_del_<?=$info['id']?>' style="<?=($info['status'] == 0 && time() > $info['end_time'])? "background-color:#F9EDED" : '' ?>">
                <td class='col-md-3'><?=$info['companyname']?></td>
                <td class="col-md-1"><?=$info['order_count']; ?></td>
                <td class="col-md-2"><?=$info['money']; ?></td>
                <td class='col-md-1 status-<?=$info['id']; ?>'><?=$info['status_name']?></td>
                <td class='col-md-3 refund_time_<?=$info['id']; ?>'><?=($info['refund_time'])?date('Y-m-d H:i:s',$info['refund_time']):'未结算'?></td>
                <td class='col-md-2'>
                    <span><a href="companyaccountinfo?id=<?=$info['id']?>&cid=<?=$info['cid']?>">查看订单</a></span>
                    <?php if ($this->rbac == '*' ? true :(in_array('addressoffice_updatestatus', $this->rbac['action']))) :?>
                        <?php if ($info['status'] == 0 && time() > $info['end_time']): ?>
                            <span id='select_<?=$info['id']?>'><a style="cursor: pointer" onclick="updateStatus(<?=$info['id']?>)" paystatus="<?=$info['pay_status']; ?>" class="paybian">确认结算</a></span>
                        <?php endif; ?>
                    <?php endif;?>
                </td>
            </tr>
        <?php endforeach; ?>
        <?php endif; ?>
      </tbody>
    </table>
    <?php echo $this->paglist; ?>
</div>
<script>
$(document).on('submit','#ajaxform',function(){
    var ktime = $('#ktime').val();
    var gtime = $('#gtime').val();
    if(ktime > gtime){ alert('开始时间不能小于结束时间');return false;}
});

function updateStatus(id)
{
	if(confirm('您确定要修改该账单的状态吗？')==false) {
		return false;
	} else {
    	$.post('/addressOffice/updateStatus',{id:id,table:'company_account'},function(ev){
            if(ev) {
                $('.status-'+id).html('已结算');
                $('.refund_time_'+id).html(ev.substr(1,ev.length-2));
            }
            $('#select_'+id).remove();
            alert('修改成功!');
        });
	}
}

function show(id,is_show)
{
    $.ajax({
       type: "POST",
       url: "upShow",
       dataType: "json",
       data: "id="+id+"&is_show="+is_show,
       success: function(data){
           if (data == 1) {
                $("#is_show_"+id).children('span').remove();
                $("#is_show_"+id).append("<span class='glyphicon glyphicon-remove btn btn-default' onclick='show("+id+" ,1)' data-toggle='tooltip' data-placement='bottom' title='下架'></span>");alert('修改成功');
           } else if(data == 0) {
                $("#is_show_"+id).children('span').remove();
                $("#is_show_"+id).append("<span class='glyphicon glyphicon-ok btn btn-default' onclick='show("+id+" ,0)' data-toggle='tooltip' data-placement='bottom' title='上架'></span>");alert('修改成功');
           } 
           if (data == 400) {
               alert('修改失败');
           }
        
       }
    });
}

function del(id,is_delete)
{
    $.ajax({
        type: "POST",
        url: "delete",
        dataType: "json",
        data: "id="+id+"&is_delete="+is_delete,
        success: function(data){
            if (data == 200) {
                $("#is_del_"+id).remove();
                $("#modal").append('<div class="col-md-3"></div><div class="col-md-6" style="margin-top: 60px"><div class="alert alert-success" role="alert"><p>删除成功</p></div></div><div class="col-md-3"></div>');
                setTimeout(function(){$("#modal").modal("hide")},2000);
            }
            if (data == 400) {
                alert('请重试');
            }
        }
     });
}

</script>
