<script src="/js/thumbnails.js" type="text/javascript"></script>
<nav class="col-md-2 hidden-print dev-sidebar">
    <?php include(dirname(__FILE__) . '/../sys/dev_nav.phtml')?>
</nav>
<style>
.s{color:red;}
td,th{text-align: center;}
</style>

<div class="col-md-10">
    <ol class="breadcrumb">
      <li><a href="addressOfficeList">地区公司管理</a></li>
      <li class="active">详情信息</li>
    </ol>
    <ul class="nav nav-pills">
      <li role="presentation"><a href="addressOfficeList">分公司列表</a></li>
	  <li role="presentation" class="active"><a href="javascript:void(0)">详情信息</a></li>
    </ul>
    <br>
    <br>
    <div id="yw3" class="tabs-right">
        <ul id="yw4" class="nav nav-tabs">
            <li class="active"><a data-toggle="tab" href="#yw3_tab_1" aria-expanded="true">详情信息</a></li>
            <li class=""><a data-toggle="tab" href="#yw3_tab_2" aria-expanded="false">公司旗下经销商</a></li>
        </ul>
        
        <div class="tab-content">
            <div id="yw3_tab_1" class="tab-pane fade active in">
                <fieldset disabled>
                    <input type='hidden' name='id' value='<?=$this->info['id']?>'>
                    <div class="form-group col-sm-12">
                        <label class="col-sm-2 control-label">地区</label>
                        <div class="col-sm-3">
                            <?php echo $this->jiliancaidan ?>
                        </div>
                    </div>
                    <div class="form-group col-sm-12">
                		<label class="col-sm-2 control-label" for="Bingtuan_goodsName">分公司名称</label>
                        <div class="col-sm-3">
                			<input type="text" class="form-control" name='companyname' value='<?=$this->info['companyname']?>'><span></span>
                        </div>
                    </div>
                    <div class="form-group col-sm-12">
                        <label class="col-sm-2 control-label">公司法人</label>
                        <div class="col-sm-3">
                          <input type="text" class="form-control" name='person' value='<?=$this->info['person']?>'>
                        </div>
                    </div>
                    <div class="form-group col-sm-12">
                        <label class="col-sm-2 control-label">联系人</label>
                        <div class="col-sm-3">
                          <input type="text" class="form-control" name='contact' value='<?=$this->info['contact']?>'>
                        </div>
                    </div>
                    <div class="form-group col-sm-12">
                        <label class="col-sm-2 control-label">联系人手机</label>
                        <div class="col-sm-3">
                          <input type="text" class="form-control" name='mobile' value='<?=$this->info['mobile']?>'>
                        </div>
                    </div>
                    <div class="form-group col-sm-12">
                        <label class="col-sm-2 control-label">公司描述</label>
                        <div class="col-sm-5">
                          <textarea class="form-control" name='describe' rows="4" cols='4'><?=$this->info['describe']?></textarea>
                        </div>
                    </div>
                    <div class="form-group col-sm-12">
                        <label class="col-sm-2 control-label">运营状态</label>
                        <div class="col-md-3">
                            <select name="status" class="form-control">
                            	<option value="1" <?=($this->info['status']==1)?'selected="selected"':'';?> >营业中</option>
                            	<option value="0" <?=($this->info['status']==0)?'selected="selected"':'';?>>暂停营业</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group col-sm-12">
                        <label class="col-sm-2 control-label">营业执照</label>
                        <div class="col-md-3">
                            <a href='<?=$this->info['license']?>' target='_blank'>
                                <img src="<?=$this->info['license']?>" alt="加载中..." class="img-rounded" width='300px' height='200px'>
                            </a>
                        </div>
                    </div>
                </fieldset>
            </div>
            <div id="yw3_tab_2" class="tab-pane fade in">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>经销商名称</th>
                            <th>联系人</th>
                            <th>电话</th>
                            <th>状态</th>
                            <th>创建时间</th>
                        </tr>
                    </thead>
                    
                    <?php 
                        if ($this->warehouse) :
                            foreach ($this->warehouse as $k => $v): 
                    ?>
                        <tr onclick="location.href='/warehouse/warehouseInfo?id=<?=$v['id']?>'" style='cursor:pointer'>
                            <td class='col-md-3'><?=$v['warehousename']?></td>
                            <td class='col-md-2'><?=$v['contact']?></td>
                            <td class='col-md-2'><?=$v['mobile']?></td>
                            <td class='col-md-2'><?=$v['status']?></td>
                            <td class='col-md-3'><?=$v['create_time']?></td>
                        </tr>
                    <?php 
                            endforeach;
                        endif;
                    ?>
                </table>
            </div>
        </div>
    </div>
</div>
