<nav class="col-md-2 hidden-print dev-sidebar">
    <?php include(dirname(__FILE__) . '/../sys/dev_nav.phtml')?>
</nav>
<script src="/js/thumbnails.js" type="text/javascript"></script>
<script src="/laydate/laydate.js" type="text/javascript"></script>
<script>
    laydate.skin('danlan')
</script>
<style>
th {text-align: center;}
td>div{width:29%;float:left;padding:0.3em}
td>input{width:12%;}
.current{color:red;}
</style>
<div class="col-md-10">
    <ol class="breadcrumb">
      <li><a href="warehouseaccountlist">经销商账单管理</a></li>
      <li class="active">经销商账单详情</li>
    </ol>
    <div style="height:20px;"></div>
    <table class="table table-hover" style="text-align: center;">
    <h4>应结金额支付方式</h4>
    <thead>
        <tr>
            <th>账单日期</th>
            <th>应结金额</th>
            <th>=</th>
            <th>微信</th>
            <th>+</th>
            <th>微信公众号</th>
            <th>+</th>
            <th>支付宝</th>
            <th>+</th>
            <th>易极付</th>
        </tr>
    </thead>
      <tbody>
        <?php if ($this->list): ?>
        <tr>
            <td class='col-md-2'><?=date('Y-m-d', $this->list['addTime'])?></td>
            <td class="col-md-1"><?=sprintf('%.2f', $this->list['tatolMoney'] - $this->list['refundMoney']); ?></td>
            <td class="col-md-1">=</td>
            <td class='col-md-1'><?=$this->list['wechatMoney']?></td>
            <td class="col-md-1">+</td>
            <td class='col-md-1'><?=$this->list['wechatPublicMoney']?></td>
            <td class="col-md-1">+</td>
            <td class='col-md-2'><?=$this->list['aliPayMoney']?></td>
            <td class="col-md-1">+</td>
            <td class='col-md-2'><?=$this->list['yijiPayMoney']?></td>
        </tr>
        <?php endif; ?>
      </tbody>
    </table>

    <div style="height:20px;"></div>
    <table class="table table-hover" style="text-align: center;">
        <h4>应结订单明细</h4>
        <thead>
        <tr>
            <th>下单日期</th>
            <th>订单号</th>
            <th>金额</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        <?php if ($this->vlist): ?>
            <?php foreach($this->vlist as $value): ?>
                <tr>
                    <td class='col-md-2'><?=date('Y-m-d', $value['add_time'])?></td>
                    <td class="col-md-3"><?=$value['order_number'] ?></td>
                    <td class="col-md-1"><?=$value['goods_amount'] ?></td>
                    <td class='col-md-1'><a href="/orders/orderInfo?order_id=<?=$value['id']?>">查看详情</a></td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
        <tr>
            <td class='col-md-2'>合计</td>
            <td class="col-md-3"><?=count($this->vlist); ?>笔</td>
            <td class="col-md-1"><?=sprintf('%.2f', $this->list['tatolMoney'] - $this->list['refundMoney']); ?>元</td>
            <td class='col-md-1'></td>
        </tr>
        </tbody>
    </table>

    <div style="height:20px;"></div>
    <table class="table table-hover" style="text-align: center;">
        <h4>退款订单明细</h4>
        <thead>
        <tr>
            <th>下单日期</th>
            <th>订单号</th>
            <th>金额</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        <?php if ($this->rlist): ?>
            <?php foreach($this->rlist as $value): ?>
                <tr>
                    <td class='col-md-2'><?=date('Y-m-d', $value['add_time'])?></td>
                    <td class="col-md-3"><?=$value['order_number'] ?></td>
                    <td class="col-md-1"><?=$value['goods_amount'] ?></td>
                    <td class='col-md-1'><a href="/orders/orderInfo?order_id=<?=$value['id']?>">查看详情</a></td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
        <tr>
            <td class='col-md-2'>合计</td>
            <td class="col-md-3"><?=count($this->rlist); ?>笔</td>
            <td class="col-md-1"><?=$this->list['refundMoney']; ?>元</td>
            <td class='col-md-1'></td>
        </tr>
        </tbody>
    </table>

    <div class="row">
        <div class="col-xs-12 col-md-8"></div>
        <div class="col-xs-6 col-md-4 h4">订单数量总计：<?= count($this->rlist) + count($this->vlist)?></div>
        <div class="col-xs-12 col-md-8"></div>
        <div class="col-xs-6 col-md-4 h4">结算金额总计：<span class='glyphicon glyphicon-yen'><?=sprintf('%.2f', $this->list['tatolMoney'] - $this->list['refundMoney']);  ?></span></div>
    </div>
</div>
