 <?php include(dirname(__FILE__) . '/../sys/header.phtml')?>
     <script type="text/javascript" src="/js/baidu_count.js"></script>
	<header class="bar bar-nav bg-bule b-n">
		<a href="/setacc/index" class="icon icon-goback pull-left"></a>
		<h1 class="title c-white">关于我们</h1>
	</header>
	<div class="content-box text-center mt-200" >
		<img style="display:inline" src="<?=Yaf_Registry::get('weixinurl')?>/images/car-bule.png" width="75px" height="75px" class="mb-20">
		<p class="fs-17 c-gary1">冰团e购<br>1.0.1版</p>
	</div>
	<div class="positionfixed"><p class="text-center">Copyright @2015冰团e购<br/>北京星水友联供应链管理有限责任公司</p></div>
<script type="text/javascript" src="<?=Yaf_Registry::get('weixinurl')?>/vendor/js/zepto.min.js"></script>
<script type="text/javascript" src="<?=Yaf_Registry::get('weixinurl')?>/js/tjp.js"></script>
  <?php include(dirname(__FILE__) . '/../sys/footer.phtml')?>
