<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
<meta name="format-detection" content="telephone=no">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<meta name="author" content="Tencent-TGideas">
<title>系统通知</title>
<style>
body{font-family: 'Microsoft Yahei', Tahoma, Helvetica, Arial, sans-serif; height:100%; color:#2d2d2d;}
html{font-size: 16px; height:100%}
body,p,h1,h2,dl,dt,dd{margin: 0;padding: 0;}
.wraper { padding:20px 18px;}
.wraper p { text-indent:2em; line-height:30px; margin-bottom:10px;}
</style>
</head>
<body>
<div class="wraper">
	<p><?=$this->notif['Contents']?></p>
</div>
</body>
</html>