<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title><?php echo $title ?></title>
	<meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
    <link rel="stylesheet" href="<?=Yaf_Registry::get('weixinurl')?>vendor/bootstrapv3/css/bs-col-sys.min.css" />
    <link rel="stylesheet" type="text/css" href="<?=Yaf_Registry::get('weixinurl')?>vendor/css/ratchet.min.css" />
	<link rel="stylesheet" type="text/css" href="<?=Yaf_Registry::get('weixinurl')?>css/app.css">
	<link rel="stylesheet" type="text/css" href="<?=Yaf_Registry::get('weixinurl')?>css/mycss.css" />
	 <link rel="stylesheet" type="text/css" href="<?=Yaf_Registry::get('weixinurl')?>css/swiper.min.css" />
	 <script src="/js/jquery-1.8.3.min.js"></script>
	 <script type="text/javascript" src="/js/function.js"></script>
</head>
<body class="addressbody">
