<!--  

<header class="bar bar-nav bg-bule b-n">
    <a class="icon icon-search2 pull-right"></a>
    <h1 class="title c-white">星水采购平台</h1>
</header>
-->
<nav class="bar bar-tab nav-bar">
    <a class="tab-item active" href="/goods/list">
        <span class="icon icon-market"></span>
        <span class="tab-label">冰团商城</span>
    </a>
    <a class="tab-item shopcar2" href="/cart/index">
        <span class="icon icon-shopcar1"></span>
        <span class="tab-label">购物车</span>
        <span class="icon-circle1">0</span>
    </a>
    <a class="tab-item shopcar2" href="/setacc/index">
        <span class="icon icon-mine"></span>
        <span class="tab-label">我的账户</span>
        <span class="icon-circle2"></span>
    </a>
</nav>