 <?php include(dirname(__FILE__) . '/../sys/header.phtml')?>
     <script type="text/javascript" src="/js/baidu_count.js"></script>
	<header class="bar bar-nav bg-bule b-n">
		<a href="./qmessage" class="icon icon-goback pull-left"></a>	
		<h1 class="title c-white">活动详情</h1>
	</header>
	<div class="activity-title top-nav content-box clearfix">
		<div class="w-70 pull-left">
			<h3 ><?=$titles?></h3>
		</div>
		<div class="w-30 pull-right">
			<p class="time text-right"><?=$times?></p>
		</div>
	</div>
	<div class="content-box content acticity-content">
		<p><?=$connect?></p>
	</div>
 <?php include(dirname(__FILE__) . '/../sys/footer.phtml')?>
