 <?php include(dirname(__FILE__) . '/../sys/header.phtml')?>
     <script type="text/javascript" src="/js/baidu_count.js"></script>
	<header class="bar bar-nav bg-bule b-n">
		<a href="/setacc/index" class="icon icon-goback pull-left"></a>
		<a href="#" class=" pull-right edit">编辑</a>
		<h1 class="title c-white">消息</h1>
	</header>
	<div class="segmented-control top-nav">
		<a class="control-item" href="./qmessage">
		   		全部消息
		</a>
		<a class="control-item " href="./dmessage">
		    	订单消息
		</a>
		<a class="control-item active" href="./zmessage">
		    	账单消息
		</a>
		<a class="control-item " href="./gmessage">
		    	官方消息
		</a>
	</div>
	
	<div class="order-box  content">
	  <div  class="control-content  active">
	  	<ul >
	  		<li>
	  			<a class="content-box" href="./zinfo">
	  				<div class="row">
	  					<div class="col-xs-8">
    	  						<h3 class="order red">蒙牛优惠券已放入您的账户请查收！</h3>
    	  						<p class="d-des">两张蒙牛优惠券已放入您的账户两张蒙牛优惠券已放入您的账户</p>
	  					</div>
	  					<div class="col-xs-4 text-right text-right">
	  						<p class="time">2015-11-14</p>
	  						<p>账单消息</p>
	  					</div>
	  				</div>
	  			</a>		
	  		</li>
	  		<li>
	  			<a class="content-box" href="./zinfo">
	  				<div class="row">
	  					<div class="col-xs-8">
	  						<h3 class="order">蒙牛优惠券已放入您的账户请查收！</h3>
	  						<p class="d-des">两张蒙牛优惠券已放入您的账户两张蒙牛优惠券已放入您的账户</p>
	  					</div>
	  					<div class="col-xs-4 text-right text-right">
	  						<p class="time">2015-11-14</p>
	  						<p>账单消息</p>
	  					</div>
	  				</div>
	  			</a>		
	  		</li>
	  		<li>
	  			<a class="content-box" href="./zinfo">
	  				<div class="row">
	  					<div class="col-xs-8">
	  						<h3 class="order red">蒙牛优惠券已放入您的账户请查收！</h3>
	  						<p class="d-des">两张蒙牛优惠券已放入您的账户两张蒙牛优惠券已放入您的账户</p>
	  					</div>
	  					<div class="col-xs-4 text-right text-right">
	  						<p class="time">2015-11-14</p>
	  						<p>账单消息</p>
	  					</div>
	  				</div>
	  			</a>		
	  		</li>
	  		<li>
	  			<a class="content-box" href="./zinfo">
	  				<div class="row">
	  					<div class="col-xs-8">
	  						<h3 class="order">蒙牛优惠券已放入您的账户请查收！</h3>
	  						<p class="d-des">两张蒙牛优惠券已放入您的账户两张蒙牛优惠券已放入您的账户</p>
	  					</div>
	  					<div class="col-xs-4 text-right text-right">
	  						<p class="time">2015-11-14</p>
	  						<p>账单消息</p>
	  					</div>
	  				</div>
	  			</a>		
	  		</li>
	  		<li>
	  			<a class="content-box" href="./zinfo">
	  				<div class="row">
	  					<div class="col-xs-8">
	  						<h3 class="order">蒙牛优惠券已放入您的账户请查收！</h3>
	  						<p class="d-des">两张蒙牛优惠券已放入您的账户两张蒙牛优惠券已放入您的账户</p>
	  					</div>
	  					<div class="col-xs-4 text-right text-right">
	  						<p class="time">2015-11-14</p>
	  						<p>账单消息</p>
	  					</div>
	  				</div>
	  			</a>		
	  		</li>
	  		<li>
	  			<a class="content-box" href="./zinfo">
	  				<div class="row">
	  					<div class="col-xs-8">
	  						<h3 class="order">蒙牛优惠券已放入您的账户请查收！</h3>
	  						<p class="d-des">两张蒙牛优惠券已放入您的账户两张蒙牛优惠券已放入您的账户</p>
	  					</div>
	  					<div class="col-xs-4 text-right text-right">
	  						<p class="time">2015-11-14</p>
	  						<p>账单消息</p>
	  					</div>
	  				</div>
	  			</a>		
	  		</li>
	  		<li>
	  			<a class="content-box" href="./zinfo">
	  				<div class="row">
	  					<div class="col-xs-8">
	  						<h3 class="order red">蒙牛优惠券已放入您的账户请查收！</h3>
	  						<p class="d-des">两张蒙牛优惠券已放入您的账户两张蒙牛优惠券已放入您的账户</p>
	  					</div>
	  					<div class="col-xs-4 text-right text-right">
	  						<p class="time">2015-11-14</p>
	  						<p>账单消息</p>
	  					</div>
	  				</div>
	  			</a>		
	  		</li>
	  		<li>
	  			<a class="content-box" href="./zinfo">
	  				<div class="row">
	  					<div class="col-xs-8">
	  						<h3 class="order red">蒙牛优惠券已放入您的账户请查收！</h3>
	  						<p class="d-des">两张蒙牛优惠券已放入您的账户两张蒙牛优惠券已放入您的账户</p>
	  					</div>
	  					<div class="col-xs-4 text-right text-right">
	  						<p class="time">2015-11-14</p>
	  						<p>账单消息</p>
	  					</div>
	  				</div>
	  			</a>		
	  		</li>
	  	</ul>
	  </div>
	</div>
 <?php include(dirname(__FILE__) . '/../sys/footer.phtml')?>
