<script src="/laydate/laydate.js" type="text/javascript"></script>
<script src="/js/multiselect.js" type="text/javascript"></script>
<nav class="col-md-2 hidden-print dev-sidebar">
    <?php include(dirname(__FILE__) . '/../sys/dev_nav.phtml')?>
</nav>
<style>
th {text-align: center;}
</style>
<script>
    laydate.skin('danlan')
</script>
<!-- 代金券详情 -->
<div class="col-md-10">
    <ol class="breadcrumb">
      <li><a href="#">品牌活动管理</a></li>
      <li class="active">添加品牌活动</li>
    </ol>
    <ul class="nav nav-pills">
      <li role="presentation" class=""><a href="list">品牌活动列表</a></li>
      <li role="presentation" class='active'><a href="javascript:void(0)">添加品牌活动</a></li>
    </ul>
    <br>
    <div id='errors'></div>
    <form method="post" action="javascript:void(0)" id="post-form" class="form-horizontal col-sm-12">
        <div class="form-group col-sm-12">
            <label class="col-sm-2 control-label">公司<span class='s'> *</span></label>
            <div class="col-sm-4">
                <select name="cid" class='form-control' id='cid'>
                    <?php foreach($this->getCompanyList as $k => $v){ ?>
                        <option value="<?=$v['id']?>" <?= ($this->info['cid'] == $v['id']) ? 'selected=selected' :'' ?>><?=$v['name']; ?></option>
                    <?php } ?>
                </select>
            </div>
        </div>
        <div class="form-group col-sm-12">
            <label class="col-sm-2 control-label">品牌<span class='s'> *</span></label>
            <div class="col-sm-4">
                <select name="activity_brand_id" class='form-control' id='activity_brand_id'>
                    <option value="0">请选择</option>
                    <?php foreach($this->getBrand as $bv){ ?>
                        <option value="<?= $bv['id']; ?>" <?= ($this->info['activity_brand_id'] == $bv['id']) ? 'selected=selected' :'' ?>><?= $bv['name']; ?></option>
                    <?php } ?>
                </select>
            </div>
        </div>
        <div class="form-group col-sm-12">
            <label class="col-sm-2 control-label">活动名称<span class='s'> *</span></label>
            <div class="col-md-4">
                <input class="form-control" type="text" name="name" value="<?= $this->info['name']; ?>" id="name">
            </div> 
        </div>
        <div class="form-group col-sm-12">
            <label class="col-sm-2 control-label">排序<span class='s'> *</span></label>
            <div class="col-md-4">
                <input class="form-control" type="text" name="order" value="<?= $this->info['order']; ?>" id="order">
            </div> 
        </div>
        <div class="form-group col-sm-12">
            <label class="col-sm-2 control-label">活动时间<span class='s'> *</span></label>
            <div class="col-md-3" style='float:left'>
                <div class="input-group">
                    <div class="input-group-addon">开始</div>
                    <input type="text" class='form-control' placeholder="开始时间" onclick="laydate()" name="start_time" value='<?=$this->info['start_time']?>'>
                </div>
            </div>
            <div class="col-md-3" style='float:left'>
                <div class="input-group">
                    <div class="input-group-addon">结束</div>
                    <input name="end_time" class='form-control' type="text" placeholder="结束时间" onclick="laydate()" value='<?=$this->info['end_time']?>'>
                </div>
            </div>
        </div>
        <div class="form-group col-sm-12">
            <label class="col-sm-2 control-label">活动描述<span class='s'> *</span></label>
            <div class="col-md-7">
                <textarea class="form-control" rows="4" name="description"><?= $this->info['description']; ?></textarea>
            </div>
        </div>
        
        <div class="form-group col-sm-12">
            <label class="col-sm-2 control-label">商品搜索<span class='s'> *</span></label>
            <div class="col-sm-3">
                <input class="form-control search" type="text" id="goods-keyword" placeholder="商品关键词">
            </div>
            <button class="btn btn-primary" type="button" id="goods-search">搜索</button>
        </div>
        <div class="form-group col-sm-12" style='margin-left: 0px;width:120%'>
        	<div class="col-xs-5" style='padding-left: 0px;padding-right: 0px;width: 45%'>
        		<select id="keepRenderingSort" class="form-control" size="8" multiple="multiple">
        		</select>
        	</div>
        	
        	<div class="col-xs-1" style='padding-left: 0px;padding-right: 0px;'>
        	    <input type='text' placeholder="活动价格" id='activity_goods_money' class='form-control'>
        		<button type="button" id="keepRenderingSort_rightAll" class="btn btn-default btn-block"><i class="glyphicon glyphicon-forward"></i></button>
        		<button type="button" id="keepRenderingSort_rightSelected" class="btn btn-default btn-block"><i class="glyphicon glyphicon-chevron-right"></i></button>
        		<button type="button" id="keepRenderingSort_leftSelected" class="btn btn-default btn-block"><i class="glyphicon glyphicon-chevron-left"></i></button>
        		<button type="button" id="keepRenderingSort_leftAll" class="btn btn-default btn-block"><i class="glyphicon glyphicon-backward"></i></button>
        	</div>
        	
        	<div class="col-xs-5" style='padding-left: 0px;padding-right: 0px;width: 45%'>
        		<select id="keepRenderingSort_to" class="form-control" size="8" multiple="multiple"></select>
        	</div>
        </div>
        <div class="field-box actions text-center" >
            <input type="hidden" value="<?=$this->info['id'];?>" name='id' id="id" />
            <input type="hidden" value="" name='goods_list' id="result" />
            <input type="submit" class="btn btn-primary" value="提交活动信息">
        </div>
    </form>
</div>

<script type="text/javascript">
jQuery(document).ready(function($) {
	$('#keepRenderingSort').multiselect({
		keepRenderingSort: true
	});
});

$('#cid').change(function(){
	$('#keepRenderingSort').empty();
	$('#keepRenderingSort_to').empty();
});

$('#goods-search').click(function(){
    var activity_brand_id = $('#activity_brand_id').val();
	if (activity_brand_id == 0) {
		alert('请选择品牌');
		return false;
	}
	
	var company = $('#cid').val();
	var id = $('#id').val();
	var keyword = $('#goods-keyword').val();
	var result = $('#result').val();
    $.ajax({
        type: "POST",
        url: "goodsSearch",
        dataType: "json",
        data: "company_id="+company+"&goodsName="+keyword+'&result='+result+'&id='+id+'&activity_brand_id='+activity_brand_id,
        success: function(data){
        	$('#keepRenderingSort').empty();
        	$('#keepRenderingSort').append(data);
        }
     });
});
$(document).on('submit','#post-form',function(){
	$.ajax({
        type: "POST",
        url:'add',
        dataType: "json",
        data:$('#post-form').serialize(),// formid
        success: function(data) {
            if (data == 200) {
                alert('提交成功');
                window.location.href = 'list';
            } else {
            	$('#errors').empty();
            	$('#errors').append("<div class='alert alert-danger alert-dismissible' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button><strong>"+data.error+"</strong></div>");
            }
        },
        error: function(request) {
        	$('#errors').empty();
        	$('#errors').append("<div class='alert alert-danger alert-dismissible' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button><strong>提交失败</strong></div>");
        }
    });
});
</script>