<link rel="stylesheet" type="text/css" href="/diyUpload/css/webuploader.css">
<link rel="stylesheet" type="text/css" href="/diyUpload/css/diyUpload.css">
<script type="text/javascript" src="/diyUpload/js/webuploader.html5only.min.js"></script>
<script type="text/javascript" src="/diyUpload/js/diyUpload.js"></script>
<script src="/js/thumbnails.js" type="text/javascript"></script>
<script src="/js/jquery.sortable.js" type="text/javascript"></script>
<script src="/js/ajaxfileupload.js"></script>
<script src="/laydate/laydate.js" type="text/javascript"></script>
<style>
.left {padding-left: 0px;}
ul {-webkit-padding-start: 0px;margin-bottom:0}
.highlight{padding:4px;margin-right: 10px; margin-left: 0;}
.center-vertical {
    position:relative;
    top:50%;
    transform:translateY(-50%);
}
</style>
<script>
    laydate.skin('danlan')
</script>
<div id="yw3" class="tabs-right">
    <ul id="yw4" class="nav nav-tabs">
        <li class="<?php echo (isset($_GET['right_nav']) && $_GET['right_nav']== 'yw3_tab_1'?'active':'')?>" onclick="window.location.href='<?=substr($_SERVER['REQUEST_URI'],0,strlen($_SERVER['REQUEST_URI'])-1);?>1'"><a data-toggle="tab" href="#yw3_tab_1" <?php echo (isset($_GET['right_nav']) && $_GET['right_nav']=='yw3_tab_1' ?'aria-expanded="true"':'aria-expanded="false"')?>>商品信息</a></li>
        <li class="<?php echo (isset($_GET['right_nav']) && $_GET['right_nav']== 'yw3_tab_3'?'active':'')?>" onclick="window.location.href='<?=substr($_SERVER['REQUEST_URI'],0,strlen($_SERVER['REQUEST_URI'])-1);?>3'"><a data-toggle="tab" href="#yw3_tab_3" <?php echo (isset($_GET['right_nav']) && $_GET['right_nav']=='yw3_tab_3' ?'aria-expanded="true"':'aria-expanded="false"')?>>商品头图</a></li>
        <li class="<?php echo (isset($_GET['right_nav']) && $_GET['right_nav']== 'yw3_tab_2'?'active':'')?>" onclick="window.location.href='<?=substr($_SERVER['REQUEST_URI'],0,strlen($_SERVER['REQUEST_URI'])-1);?>2'"><a data-toggle="tab" href="#yw3_tab_2" <?php echo (isset($_GET['right_nav']) && $_GET['right_nav']=='yw3_tab_2' ?'aria-expanded="true"':'aria-expanded="false"')?>>详情图</a></li>
    </ul>
    <div class="tab-content">
        <div id="yw3_tab_1" class="tab-pane fade <?php echo (isset($_GET['right_nav']) && $_GET['right_nav']== 'yw3_tab_1'?'active':'')?> in">
            <form action='update?id=<?php echo $_GET['id'] ?>&pid=<?php echo $_GET['pid'] ?>&right_nav=<?php echo $_GET['right_nav'] ?>' method="POST" id='ajaxform' enctype="multipart/form-data" class="form-horizontal col-sm-12">
                <input type="hidden" name='id' value='<?=$this->goods['id']?>'>
                <div class="form-group col-sm-12">
                    <label class="col-sm-2 control-label" for="Bingtuan_goodsName">商品名称<span class='s'> *</span></label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control" name='goods_name' value='<?=$this->goods['goods_name']?>'><span></span>
                    </div>
                  </div>
                <div class="form-group col-sm-12">
                    <label class="col-sm-2 control-label" for="Bingtuan_goodsabbreviation">商品简称<span class='s'> *</span></label>
                    <div class="col-sm-3">
                        <input type="text" class="form-control" name='goods_abbreviation' value='<?=$this->goods['goods_abbreviation']?>'><span></span>
                    </div>
                </div>
                  <div class="form-group col-sm-12">
                    <label class="col-sm-2 control-label">品类<span class='s'> *</span></label>
                    <div class="col-sm-3">
                        
                        <select class="form-control" name="goods_type" id='goods_type'>
                          <option value="">请选择</option>
                          <?php foreach ($this->goods_type as $key): ?>
                                    <option value="<?= $key['id'] ?>" 
                                    <?php if($this->goods['goods_type'] == $key['id']): ?> 
                                        selected="selected" 
                                    <?php endif; ?> 
                                    ><?= $key['name'] ?></option>
                          <?php endforeach; ?>
                        </select>
                    </div>
                  </div>
                  <div class="form-group col-sm-12">
                    <label class="col-sm-2 control-label">品牌<span class='s'> *</span></label>
                    <div class="col-sm-3">
                        <select class="form-control" name="brand_id" id='brand_id'>
                          <option value="">请选择</option>
                          <?php foreach ($this->brand as $key): ?>
                                    <option value="<?= $key['id'] ?>" 
                                    <?php if($this->goods['brand_id'] == $key['id']): ?> 
                                        selected="selected" 
                                    <?php endif; ?> 
                                    ><?= $key['name'] ?></option>
                          <?php endforeach; ?>
                        </select>
                    </div>
                  </div>
                  <div class="form-group col-sm-12">
                    <label class="col-sm-2 control-label">公司<span class='s'> *</span></label>
                    <div class="col-sm-4">
                        <select name="cid" class='form-control' <?=($this->rbac == '*' ? '' : 'disabled')?>>
                            <?php foreach($this->getCompanyList as $k => $v){ ?>
                                <option value="<?=$v['id']?>" <?= ($this->goods['cid'] == $v['id']) ? 'selected=selected' :'' ?>><?=$v['name']; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                  </div>
                  <div class="form-group col-sm-12">
                    <label class="col-sm-2 control-label">价格<span class='s'> *</span></label>
                    <div class="col-sm-10" id="description">
                        <div class="col-sm-12 left">
                            <span class='col-xs-2 left'>市场参考价</span><input type="text" class="form-group" name='city_price' value='<?=$this->goods['city_price']?>'>
                            <?php if($this->goods['cid'] == 1): ?>
                                <span><input type="checkbox" name="city_price_all_company" value="1" style="margin-left:30px !important;">&nbsp;全部分公司</span>
                            <?php endif ?>
                        </div>
                        <div class="col-sm-12 left">
                            <span class='col-xs-2 left'>销售价</span><input type="text" class="form-group" name='all_price' value='<?=$this->goods['all_price']?>'>
                            <?php if($this->goods['cid'] == 1): ?>
                                <span><input type="checkbox" name="all_price_all_company" value="1" style="margin-left:30px !important;">&nbsp;全部分公司</span>
                            <?php endif ?>
                        </div>
                    </div>
                  </div>
                  
                  <div class="form-group col-sm-12">
                    <label class="col-sm-2 control-label">优惠劵</label>
                    <div class="col-xs-10">
                        <?php if ($this->coupons):?>
                            <?php foreach ($this->coupons as $k=>$v): ?>
                                <label class="checkbox-inline">
                                    <input type="checkbox" name='coupons' 
                                      <?php if(@in_array($k, (empty($this->goods['coupons'])?$this->couponsArray:$this->goods['coupons'])) == $k): ?> 
                                        checked="checked"
                                       <?php endif; ?> 
                                     value="<?=$k?>"> <?=$v?>
                                </label>
                            <?php endforeach; ?>
                        <?php endif;?>
                    </div>
                  </div>
                  
                  <div class="form-group col-sm-12">
                    <label class="col-sm-2 control-label">库存<span class='s'> *</span></label>
                    <div class="col-sm-2">
                      <input type="text" class="form-control" name='amount' value='<?=$this->goods['amount']?>'>
                    </div>
                      <?php if($this->goods['cid'] == 1): ?>
                            <div class="col-sm-2" style="line-height:32px; padding-left:0px;">
                                <input type="checkbox" name="all_amount" value="1">&nbsp;全部分公司
                            </div>
                      <?php endif ?>
                  </div>
                  <div class="form-group col-sm-12">
                    <label class="col-sm-2 control-label">商品重量</label>
                    <div class="col-sm-3">
                        <div class="input-group">
                            <input type="text" class="form-control" name='goods_weight' value='<?=($this->goods['goods_weight'])?$this->goods['goods_weight']:''?>'>
                        </div>
                    </div>
                  </div>
                  <div class="form-group col-sm-12">
                    <label class="col-sm-2 control-label">单位<span class='s'> *</span></label>
                    <div class="col-sm-3">
                      <input type="text" class="form-control" name='unit' value='<?=$this->goods['unit']?>'>
                    </div>
                  </div>
                <div class="form-group col-sm-12">
                  <label class="col-sm-2 control-label">包装规格<span class='s'> *</span></label>
                  <div class="col-sm-5">
                    <input type="text" class="form-control" name='standard' value='<?=$this->goods['standard']?>'>
                  </div>
                </div>
                <div class="form-group col-sm-12">
                  <label class="col-sm-2 control-label">生产时间</label>
                  <div class="col-sm-3">
                <input type="text" class="form-control" name='production_time' onclick="laydate()" placeholder="生产时间" value='<?=($this->goods['production_time'])?date('Y-m-d', $this->goods['production_time']):''?>'>
                  </div>
                </div>
                <div class="form-group col-sm-12">
                  <label class="col-sm-2 control-label">贮存条件</label>
                  <div class="col-sm-5">
                    <input type="text" class="form-control" name='storage' value='<?=$this->goods['storage']?>'>
                  </div>
                </div>
                <div class="form-group col-sm-12">
                  <label class="col-sm-2 control-label">保质期</label>
                  <div class="col-sm-3">
                    <input type="text" class="form-control" name='shelf_life' placeholder="保质期" value='<?=($this->goods['shelf_life'])?$this->goods['shelf_life']:''?>'>
                  </div>
                </div>
                  <div class="form-group col-sm-12">
                    <label class="col-sm-2 control-label">包装方式</label>
                    <div class="col-sm-3">
                      <input type="text" class="form-control" name='packaging' value='<?=$this->goods['packaging']?>'>
                    </div>
                  </div>
                  <div class="form-group col-sm-12">
                    <label class="col-sm-2 control-label">产地</label>
                    <div class="col-sm-3">
                      <input type="text" class="form-control" name='origin' value='<?=$this->goods['origin']?>'>
                    </div>
                  </div>
                  <div class="form-group col-sm-12">
                    <label class="col-sm-2 control-label">省份</label>
                    <div class="col-sm-3">
                      <input type="text" class="form-control" name='province' value='<?=$this->goods['province']?>'>
                    </div>
                  </div>
                  <div class="form-group col-sm-12">
                    <label class="col-sm-2 control-label">详细描述</label>
                    <div class="col-sm-5">
                      <textarea class="form-control" rows="3" name='goods_desc' id='goods_desc'><?=$this->goods['goods_desc']?></textarea>
                    </div>
                  </div>
                  <div class="form-group col-sm-12">
                    <label class="col-sm-2 control-label">商品缩略图<span class='s'> *</span></label>
                        <!--上传图片开始 -->
                        <div class="col-sm-10" id='uploadImg'>
                           <img id="goods_images" src="<?php echo (!empty($this->goods['goods_img'])?$this->goods['goods_img']:'/img/uploadButton.png') ?>" style="height:100px;width:100px;position:absolute; border-radius: 3px;" alt='加载中...'/>
                          <input type="file" id="goods_img" name="goods_img" style="padding-left: 0px; opacity: 0;height: 100px;width: 100px;"/>
                            <p class="help-block s">上传图片宽高：380*388</p>
                        </div>
                        <!--上传图片结束-->
                  </div>
                <div class="form-group col-sm-12">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-success">提交</button>
                    </div>
                </div>
            </form>
        </div>
        
        <div id="yw3_tab_2" class="tab-pane fade <?php echo (isset($_GET['right_nav']) && $_GET['right_nav']== 'yw3_tab_2'?'active':'')?> in">
        <form method='POST' enctype='multipart/form-data' >
              <div class="form-group col-sm-12">
<!--                 <label class="col-sm-2 control-label">详情图<span class='s'> *</span></label> -->
                <div class="col-sm-12" style='padding-left:0'>
                    <div class="controls">
                        <input type="file" style="display: none" id='goods_desc_img' name="goods_desc_img[]" multiple="multiple">
                        <div id="content_goods_desc_img">
                            <?php if ($this->goods['goods_desc_img']) :?>
                                <?php foreach ($this->goods['goods_desc_img'] as $k => $v) : ?>
                                    <div class="highlight" style="width: 9.3em;display: inline;float: left;" id="content_goods_desc_img_<?=$k?>">
                                        <input type='hidden' name='goodsDescImg[]' value='<?=$k?>'>
                                        <div style="width: 9.3em;position: absolute;padding-right: 9px;">
                                            <span type="button" class="btn btn-danger glyphicon glyphicon-remove" style='float: right;border-radius: 50%;line-height: 1.428571;padding: 0;width: 20px;height: 20px;' onclick="if(confirm('确定要删除吗？删除后图片不可恢复！')==false)return false; ajaxFileUpload(<?=$this->goods['id']?>,<?=$k?>,'/goods/delImg','goods_desc_img','content_goods_desc_img_<?=$k?>',2)"></span>
                                        </div>
                                       <a href='<?=$v?>' target='_blank'><img src="<?=$v?>" width="120px" height="120px"></a>
                                    </div>
                                    
                                <?php endforeach; ?>
                            <?php endif;?>
                            <div id='delete_goods_desc_img'></div>
                        </div>
                    </div>
                    <div class='col-xs-12' style='padding: 0;'>
                     <div id="uploadfile_goods_desc_img" class="webuploader-pick" style='width:8.2em;'>上传多张图片</div>
                     <div class="webuploader-pick" onclick="ajaxFileUpload(<?=$this->goods['id']?>,'','/goods/uploadImages','goods_desc_img','',2)" style='width:8.2em;background-color: #449d44;'>开始上传</div>
                    </div>
                </div>
                <!--上传图片结束-->
              </div>
              </form>
        </div>
        
        <div id="yw3_tab_3" class="tab-pane fade <?php echo (isset($_GET['right_nav']) && $_GET['right_nav']== 'yw3_tab_3'?'active':'')?> in">
        <form method='POST' enctype='multipart/form-data' >
          <div class="form-group col-sm-12">
<!--             <label class="col-sm-2 control-label">商品头图<span class='s'> *</span></label> -->
            <div class="col-sm-12" style='padding-left:0'>
                <div class="controls1">
                    <input type="file" style="display: none" id='original_img' name="original_img[]" multiple="multiple">
                    <ul id="content_original_img">
                        <?php if ($this->goods['original_img']) :?><?php foreach ($this->goods['original_img'] as $k => $v) : ?>
                            <li class="highlight list-inline" style="width: 9.3em;display: inline;float: left;" id="content_original_img_<?=$k?>">
                                <input type='hidden' name='originalImage[]' value='<?=$k?>'>
                                <div style="width: 9.3em;position: absolute;padding-right: 9px;">
                                    <span type="button" class="btn btn-danger glyphicon glyphicon-remove" style='float: right;border-radius: 50%;line-height: 1.428571;padding: 0;width: 20px;height: 20px;' onclick="if(confirm('确定要删除吗？删除后图片不可恢复！')==false)return false; ajaxFileUpload(<?=$this->goods['id']?>,<?=$k?>,'/goods/delImg','original_img','content_original_img_<?=$k?>',3)"></span>
                                </div>
                               <a href='<?=$v?>' target='_blank'><img src="<?=$v?>" width="120px" height="120px"></a>
                            </li>
                        <?php endforeach; ?><?php endif;?>
                        <div id='delete_original_img'></div>
                    </ul>
                </div>
                <div class='col-xs-12' style='padding: 0;'>
                 <div id="uploadfile_original_img" class="webuploader-pick" style='width:8.2em;'>上传多张图片</div>
                 <div class="webuploader-pick" onclick="ajaxFileUpload(<?=$this->goods['id']?>,'','/goods/uploadImages','original_img','',3)" style='width:8.2em;background-color: #449d44;'>开始上传</div>
                </div>
            </div>
            <!--上传图片结束-->
          </div>
          </form>
        </div>
    </div>
</div>
<!-- 弹出层  开始 -->
<div class="modal fade bs-example-modal-sm" id="myModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm" style="color:#000">
        <div class="modal-content" style="margin-top: 100px;">
            <div class="text-center" style="height: 80px; padding-top: 25px;padding: 25px 0 0 0;">
                <h4 id="error_message"></h4>
            </div>
            <div class="text-center" id="buttom" style="border-top:1px solid #C2C2C2;height:41px; line-height:40px">
               <div data-dismiss="modal" style="font-size:24px;" >确定</div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade bs-example-modal-sm" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm" style="color:#000">
        <div class="modal-content" style="margin-top: 100px;">
            <div class="text-center" style="height: 80px; padding: 10px 0 0 0;">
                <h3 id="error_message2"></h3>
            </div>
            <div class="text-center" style="border-top:1px solid #C2C2C2;height:41px; line-height:40px" id="buttom2">
               
            </div>
        </div>
    </div>
</div>

<!-- 弹出层  结束 -->
<script>
    var pid = '<?php echo $this->pid; ?>';
    $(function(){
        if(pid > 0 || pid == ''){
            $('form').find('input').attr("disabled", true);
            $('form').find('select').attr("disabled", true);
            $('form').find('textarea').attr("disabled", true);
            $('form').find('.btn').attr('disabled', true);
        }
    })
$(document).on('submit','#ajaxform',function(){
    var goods_name = $('input[name="goods_name"]').val();
    if(!goods_name){ alert('商品名称不能为空');return false;}
    var goods_type = $('#goods_type').val();
    if(!goods_type){ alert('品类不能为空');return false;}
    var brand_id = $('#brand_id').val();
    if(!brand_id){ alert('品牌不能为空');return false;}
    var city_price = $('input[name="city_price"]').val();
    var all_price = $('input[name="all_price"]').val();
    if(!city_price || !all_price){ alert('价格不能为空');return false;}
//     var coupons = $('input[name="coupons"]:checked').length;
//     if(coupons != 1){ alert('抱歉，此处商品只能选择一个优惠券');return false;}

    var amount = $('input[name="amount"]').val();
    if(amount < 0){ alert('库存不能小于0');return false;}
//     var goods_weight = $('input[name="goods_weight"]').val();
//     if(!goods_weight){ alert('商品重量不能为空');return false;}
    var unit = $('input[name="unit"]').val();
    if(!unit){ alert('单位不能为空');return false;}
    var standard = $("input[name='standard']").val();
    if(!standard){ alert('规格不能为空');return false;}
//     var production_time = $("input[name='production_time']").val();
//     if(!production_time){ alert('生产时间不能为空');return false;}
//     var storage = $("input[name='storage']").val();
//     if(!storage){ alert('贮存条件不能为空');return false;}
//     var shelf_life = $("input[name='shelf_life']").val();
//     if(!shelf_life){ alert('保质期不能为空');return false;}
//     var packaging = $('input[name="packaging"]').val();
//     if(!packaging){ alert('包装不能为空');return false;}
//     var origin = $('input[name="origin"]').val();
//     if(!origin){ alert('产地不能为空');return false;}
//     var province = $('input[name="province"]').val();
//     if(!province){ alert('省份不能为空');return false;}
//     var goods_desc = $('#goods_desc').val();
//     if(!goods_desc){ alert('详细描述不能为空');return false;}
    
});

// 移动图片
function changeNum()
{
    var original_img = $('input[name="originalImage[]"]');
    var imgStr = new Array();
    $.each(original_img,function(name,value) {
        imgStr[name] = value.defaultValue;
    });
    $.ajax({
        type: "POST",
        url: "upImagePlace",
        data: {imgStr:imgStr,goods_name:'original_img',goods_id:<?=$this->goods['id']?>},
        dataType: "json",
        success:function(data){
            alert(data.data);
        }
    });
}
$(function(){
    $( "#content_original_img" ).sortable().bind('sortupdate',function() {
        changeNum();
    });
});

function changeNumber()
{
    var goodsDescImg = $('input[name="goodsDescImg[]"]');
    var imgStr = new Array();
    $.each(goodsDescImg,function(name,value) {
        imgStr[name] = value.defaultValue;
    });
    $.ajax({
        type: "POST",
        url: "upImagePlace",
        data: {imgStr:imgStr,goods_name:'goods_desc_img',goods_id:<?=$this->goods['id']?>},
        dataType: "json",
        success:function(data){
            alert(data.data);
        }
    });
}
$(function(){
    $( "#content_goods_desc_img" ).sortable().bind('sortupdate',function() {
    	changeNumber();
    });
});

$("#goods_img").change(function(){
    var fileList = this.files;
    var reader = new FileReader();
    reader.readAsDataURL(fileList[0]);
    reader.onload = function(e) {
        var image = new Image();
        image.src = e.target.result;
        image.onload=function(){
//             if(image.width < 190 || image.height < 194){
//                 alert('图片宽高：'+image.width+'---'+image.height);
//                 $("#goods_img").val('');
//                 $('#goods_images').attr('src','/img/uploadButton.png');
//                 fileList = null;
//                 image = null;
//             } else {
                $('#goods_images').attr('src',image.src);
//             }
        }
    } 
});

if ($('.goods_desc_img').length >= 8) {
    $("#uploadImg").attr("style","display:none;padding-left: 2em;");
}
if ($('.good_images').length >= 8) {
    $("#uploadImg").attr("style","display:none;padding-left: 2em;");
}

$('#uploadfile_goods_desc_img').click(function() {
      $('#goods_desc_img').trigger('click');
});
var inputElement = document.getElementById("goods_desc_img");
inputElement.addEventListener("change", goods_desc_img_handleFiles, false);
function goods_desc_img_handleFiles(){
  var fileList = this.files;
  var fileStr = '';
  var dd = document.getElementById('delete_goods_desc_img');
  dd.innerHTML = '';
  var countImg = 1;
  for( var i = 0 ; i < fileList.length ; i++ ){
  	  var fileList = this.files;
      var reader = new FileReader();
      reader.readAsDataURL(fileList[i]);
      reader.onload = function(e) {
          var image = new Image();
          image.src = e.target.result;
          image.onload=function(){
              if(image.width < 828 ){ //  || image.height < 414
            	  alert('第 '+(countImg++)+' 张图片宽高错误');
            	  fileList[i] = '';
              } else {
            	    dd.innerHTML += "<div class='highlight' style='width: 9.3em;display: inline;float: left;'><img src='"+image.src+"' width='120px' height='120px'/></div>";
              }
          }
      }
    }
}
$(document).on('click','#uploadfile_original_img',function(){
	$('#original_img').trigger('click');
});
var inputElement = document.getElementById("original_img");
inputElement.addEventListener("change", original_img_handleFiles, false);
function original_img_handleFiles(){
    var fileList = this.files;
    var fileStr = '';
    var dd = document.getElementById('delete_original_img');
    dd.innerHTML = '';
    var countImg = 1;
    for( var i = 0 ; i < fileList.length ; i++ ){
  	  var fileList = this.files;
      var reader = new FileReader();
      reader.readAsDataURL(fileList[i]);
      reader.onload = function(e) {
          var image = new Image();
          image.src = e.target.result;
          image.onload=function(){
              if(image.width < 828 || image.height < 414){
            	  alert('第 '+(countImg++)+' 张图片宽高错误');
            	  fileList[i] = '';
              } else {
            	    dd.innerHTML += "<div class='highlight' style='width: 9.3em;display: inline;float: left;'><img src='"+image.src+"' width='120px' height='120px'/></div>";
              }
          }
      }
    }
}
var url = '';
function ajaxFileUpload(id,img,url,name,imgName,num) {
	$.ajaxFileUpload({
		url: url,
		type: 'POST',
		secureuri: false, //一般设置为false
		fileElementId: [name], // 上传文件的id、name属性名
		dataType: 'json', //返回值类型，一般设置为json、application/json
		data:{id:id,img:img,name:name},//一同上传的数据  
		success : function (data, status){
			if (data == 'null') {
				$('#error_message').html('请选择上传图片');
				$('#buttom').html('<div data-dismiss="modal" style="font-size:24px;" onclick="window.location.href=\'<?=substr($_SERVER['REQUEST_URI'],0,strlen($_SERVER['REQUEST_URI'])-1);?>'+num+'\'">确定</div>');
				$('#myModal').modal({backdrop: 'static', keyboard: false});
			}
			if (data == 'del') {
				$('#error_message').html('删除成功');
				$('#buttom').html('<div data-dismiss="modal" style="font-size:24px;" onclick="window.location.href=\'<?=substr($_SERVER['REQUEST_URI'],0,strlen($_SERVER['REQUEST_URI'])-1);?>'+num+'\'">确定</div>');
				$('#myModal').modal({backdrop: 'static', keyboard: false});
				$("#uploadImg").attr("style","padding-left: 2em;");
				$("#"+imgName).remove();
			}
			if (data == '200') {
				$('#error_message').html('上传成功');
				$('#buttom').html('<div data-dismiss="modal" style="font-size:24px;" onclick="window.location.href=\'<?=substr($_SERVER['REQUEST_URI'],0,strlen($_SERVER['REQUEST_URI'])-1);?>'+num+'\'">确定</div>');
				$('#myModal').modal({backdrop: 'static', keyboard: false});
			} 
			if (data == '400') {
				$('#error_message').html('上传失败');
				$('#buttom').html('<div data-dismiss="modal" style="font-size:24px;" onclick="window.location.href=\'<?=substr($_SERVER['REQUEST_URI'],0,strlen($_SERVER['REQUEST_URI'])-1);?>'+num+'\'">确定</div>');
				$('#myModal').modal({backdrop: 'static', keyboard: false});
			}
		},
		error: function(data, status, e){
			$('#myModal_loading').modal('hide');
			$('#error_message').html('失败！');
			$('#buttom').html('<div data-dismiss="modal" style="font-size:24px;" onclick="window.location.href=\'<?=substr($_SERVER['REQUEST_URI'],0,strlen($_SERVER['REQUEST_URI'])-1);?>'+num+'\'">确定</div>');
			$('#myModal').modal({backdrop: 'static', keyboard: false});
		}
	});
}

</script>