<link rel="stylesheet" type="text/css" href="/diyUpload/css/webuploader.css">
<link rel="stylesheet" type="text/css" href="/diyUpload/css/diyUpload.css">
<script type="text/javascript" src="/diyUpload/js/webuploader.html5only.min.js"></script>
<script type="text/javascript" src="/diyUpload/js/diyUpload.js"></script>
<script type="text/javascript" src="/js/bootstrap3-typeahead.min.js"></script>
<script src="/js/thumbnails.js" type="text/javascript"></script>
<script src="/laydate/laydate.js" type="text/javascript"></script>
<script>
    laydate.skin('danlan')
</script>
<style>
.left {padding-left: 0px;}
ul {-webkit-padding-start: 0px;}
.highlight{padding:4px;margin-right: 10px;}

</style>
<form action='add' id='ajaxform' method="POST" enctype="multipart/form-data" class="form-horizontal col-sm-12">
    <div class="form-group col-sm-12">
        <label class="col-sm-2 control-label" for="Bingtuan_goodsName">商品名称<span class='s'> *</span></label>
        <div class="col-sm-3">
            <input type="text" class="form-control" name='goods_name' value='<?=$this->goods['goods_name']?>'><span></span>
        </div>
    </div>
    <div class="form-group col-sm-12">
        <label class="col-sm-2 control-label" for="Bingtuan_goodsabbreviation">商品简称<span class='s'> *</span></label>
        <div class="col-sm-3">
            <input type="text" class="form-control" name='goods_abbreviation' value='<?=$this->goods['goods_abbreviation']?>'><span></span>
        </div>
    </div>
    <div class="form-group col-sm-12">
        <label class="col-sm-2 control-label">品类<span class='s'> *</span></label>
        <div class="col-sm-3">
            <input type="hidden" name="goods_type" id="goods_type">
            <input type="text" class="form-control typeahead dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown"
                   data-provide="typeahead" style="width:185px;">
            <span class="caret" style="position:absolute; left:184px; bottom:15px;"></span>
            <ul class="dropdown-menu dropdown-menu-right" role="menu" id="dropdown" aria-labelledby="dropdownMenu1"
                style="width:185px; margin-right:15px;">
                <?php foreach ($this->goods_type as $key): ?>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="javascript:void(0);"
                                               data-id="<?= $key['id'] ?>"><?= $key['name'] ?></a></li>
                <?php endforeach; ?>
            </ul>


            <!--            <select class="form-control" name="goods_type" id='goods_type'>-->
<!--                <option value="">请选择</option>-->
<!--                 --><?php //foreach ($this->goods_type as $key): ?>
<!--                    <option value="--><?//= $key['id'] ?><!--" --><?php //if($this->goods['goods_type'] == $key['id']): ?><!-- selected="selected" --><?php //endif; ?><!-- >--><?//= $key['name'] ?><!--</option>-->
<!--                 --><?php //endforeach; ?>
<!--            </select>-->

        </div>
    </div>
    <div class="form-group col-sm-12">
        <label class="col-sm-2 control-label">品牌<span class='s'> *</span></label>
        <div class="col-sm-3">
            <input type="hidden" name="brand_id" id="brand_id">
            <input type="text" class="form-control typeahead dropdown-toggle" id="dropdownMenu2" data-toggle="dropdown"
                   data-provide="typeahead" style="width:185px;">
            <span class="caret" style="position:absolute; left:184px; bottom:15px;"></span>
            <ul class="dropdown-menu dropdown-menu-right" role="menu" id="dropdown1" aria-labelledby="dropdownMenu2"
                style="width:185px; height:300px; margin-right:15px; overflow: auto;">
                <?php foreach ($this->brand as $key): ?>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="javascript:void(0);"
                                               data-id="<?= $key['id'] ?>"><?= $key['name'] ?></a></li>
                <?php endforeach; ?>
            </ul>
<!--            <select class="form-control" name="brand_id" id='brand_id'>-->
<!--                <option value="">请选择</option>-->
<!--                --><?php //foreach ($this->brand as $key): ?>
<!--                    <option value="--><?//= $key['id'] ?><!--" --><?php //if($this->goods['brand_id'] == $key['id']): ?><!-- selected="selected" --><?php //endif; ?><!-- >--><?//= $key['name'] ?><!--</option>-->
<!--                --><?php //endforeach; ?>
<!--            </select>-->
        </div>
    </div>
    <div class="form-group col-sm-12">
        <label class="col-sm-2 control-label">公司<span class='s'> *</span></label>
        <div class="col-sm-4">
            <select name="cid" class='form-control ' <?=($this->rbac == '*' ? '' : 'disabled')?> disabled>
                <?php foreach($this->getCompanyList as $k => $v){ ?>
                    <option value="<?=$v['id']?>" <?= ($this->goods['cid'] == $v['id']) ? 'selected=selected' :'' ?>><?=$v['name']; ?></option>
                <?php } ?>
            </select>
        </div>
    </div>
    <div class="form-group col-sm-12">
      <label class="col-sm-2 control-label">价格<span class='s'> *</span></label>
      <div class="col-sm-10" id="description">
      <div class="col-sm-12 left">
            <span class='col-xs-2 left'>市场参考价</span><input type="text" class="form-group roles-number" name='city_price' value='<?=$this->goods['city_price']?>'>
      </div>
      <div class="col-sm-12 left">
            <span class='col-xs-2 left'>销售价</span><input type="text" class="form-group roles-number" name='all_price' value='<?=$this->goods['all_price']?>'>
      </div>
      </div>
    </div>
    
      <div class="form-group col-sm-12">
        <label class="col-sm-2 control-label">优惠劵</label>
        <div class="col-xs-10">
            <?php foreach ($this->coupons as $k=>$v): ?>
                <label class="checkbox-inline">
                    <input type="checkbox" name='coupons' 
                          <?php if(@in_array($k, $this->goods['coupons']) == $k): ?> 
                            checked="checked"
                           <?php endif; ?> 
                     value="<?=$k?>"> <?=$v?>
                </label>
            <?php endforeach; ?>
        </div>
      </div>
    
    <div class="form-group col-sm-12">
      <label class="col-sm-2 control-label">库存<span class='s'> *</span></label>
      <div class="col-sm-3">
        <input type="text" class="form-control" name='amount' value='<?=$this->goods['amount']?>'>
      </div>
    </div>
    <div class="form-group col-sm-12">
      <label class="col-sm-2 control-label">商品重量</label>
      <div class="col-sm-3">
            <div class="input-group">
                <input type="text" class="form-control" name='goods_weight' value='<?=$this->goods['goods_weight']?>'>
            </div>
      </div>
    </div>
    <div class="form-group col-sm-12">
      <label class="col-sm-2 control-label">单位<span class='s'> *</span></label>
      <div class="col-sm-3">
        <input type="text" class="form-control" name='unit' value='<?=$this->goods['unit']?>'>
      </div>
    </div>
    <div class="form-group col-sm-12">
      <label class="col-sm-2 control-label">规格<span class='s'> *</span></label>
      <div class="col-sm-5">
        <input type="text" class="form-control" name='standard' value='<?=$this->goods['standard']?>'>
      </div>
    </div>
    <div class="form-group col-sm-12">
      <label class="col-sm-2 control-label">生产时间</label>
      <div class="col-sm-3">
    <input type="text" class="form-control" name='production_time' onclick="laydate()" placeholder="生产时间" value='<?=$this->goods['production_time']?>'>
      </div>
    </div>
    <div class="form-group col-sm-12">
      <label class="col-sm-2 control-label">贮存条件</label>
      <div class="col-sm-5">
        <input type="text" class="form-control" name='storage' value='<?=$this->goods['storage']?>'>
      </div>
    </div>
    <div class="form-group col-sm-12">
      <label class="col-sm-2 control-label">保质期</label>
      <div class="col-sm-3">
        <input type="text" class="form-control" name='shelf_life' placeholder="保质期" value='<?=$this->goods['shelf_life']?>'>
      </div>
    </div>
    <div class="form-group col-sm-12">
      <label class="col-sm-2 control-label">包装</label>
      <div class="col-sm-3">
        <input type="text" class="form-control" name='packaging' value='<?=$this->goods['packaging']?>'>
      </div>
    </div>
    <div class="form-group col-sm-12">
      <label class="col-sm-2 control-label">产地</label>
      <div class="col-sm-3">
        <input type="text" class="form-control" name='origin' value='<?=$this->goods['origin']?>'>
      </div>
    </div>
    <div class="form-group col-sm-12">
      <label class="col-sm-2 control-label">省份</label>
      <div class="col-sm-3">
        <input type="text" class="form-control" name='province' value='<?=$this->goods['province']?>'>
      </div>
    </div>
    <div class="form-group col-sm-12">
      <label class="col-sm-2 control-label">详细描述</label>
      <div class="col-sm-5">
        <textarea class="form-control" rows="3" name='goods_desc' id='goods_desc'><?=$this->goods['goods_desc']?></textarea>
      </div>
    </div>
    <div class="form-group col-sm-12">
      <label class="col-sm-2 control-label">详情图</label>
      <div class="col-sm-10">
            <div class="controls">
                <input type="file" style="display: none" id='goods_desc_img' name="goods_desc_img[]" multiple="multiple">
                <div id="content_goods_desc_img"></div>
            </div>
            <div class='col-xs-12' style='padding: 0;'>
             <div id="uploadfile_goods_desc_img" class="webuploader-pick" style='width:8.2em;'>上传多张图片</div>
             <p class="help-block s text-left">上传图片宽：828</p>
            </div>
      </div>
    </div>
    <div class="form-group col-sm-12">
        <label class="col-sm-2 control-label">商品头图<span class='s'> *</span></label>
        <div class="col-sm-10">
            <div class="controls1">
                <input type="file" style="display: none" id='original_img' name="original_img[]" multiple="multiple">
                <div id="content_original_img"></div>
            </div>
            <div class='col-xs-12' style='padding: 0;'>
             <div id="uploadfile_original_img" class="webuploader-pick" style='width:8.2em;'>上传多张图片</div>
             <p class="help-block s text-left">上传图片宽高：828*414</p>
            </div>
        </div>
    </div>
    <div class="form-group col-sm-12">
        <label class="col-sm-2 control-label">商品缩略图<span class='s'> *</span></label>
        <div class="col-sm-5">
            <img id="ImgPr" style="height:100px;width:100px;position:absolute; border-radius: 3px;background-size:100px 100px; background-image:url('/img/uploadButton.png')" />
            <input type="file" id="up" name="goods_img" multiple="multiple" style="padding-left: 0px; opacity: 0;height: 100px;width: 100px;"/>
            <p class="help-block s">上传图片宽高：380*388</p>
        </div>
    </div>
    <div class="form-group col-sm-12">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">提交</button>
        </div>
    </div>
</form>

<script>
$(document).on('submit','#ajaxform',function(){
    var goods_name = $("input[name='goods_name']").val();
    if(!goods_name){ alert('商品名称不能为空');return false;}
    var goods_type = $("#goods_type").val();
    if(!goods_type){ alert('品类不能为空');return false;}
    var brand_id = $("#brand_id").val();
    if(!brand_id){ alert('品牌不能为空');return false;}
    var city_price = $("input[name='city_price']").val();
    var all_price = $("input[name='all_price']").val();
    if(!brand_id || !all_price){ alert('价格不能为空');return false;}
    var coupons = $('input[name="coupons"]:checked').length;
    if (coupons != '') {
        if(coupons != 1){ alert('抱歉，此处商品只能选择一个优惠券');return false;}
    }
    var amount = $("input[name='amount']").val();
    if(!amount){ alert('库存不能为空');return false;}
//     var goods_weight = $("input[name='goods_weight']").val();
//     if(!goods_weight){ alert('商品重量不能为空');return false;}
    var unit = $("input[name='unit']").val();
    if(!unit){ alert('单位不能为空');return false;}
    
    var standard = $("input[name='standard']").val();
    if(!standard){ alert('规格不能为空');return false;}
    var production_time = $("input[name='production_time']").val();
//     if(!production_time){ alert('生产时间不能为空');return false;}
//     var storage = $("input[name='storage']").val();
//     if(!storage){ alert('贮存条件不能为空');return false;}
//     var shelf_life = $("input[name='shelf_life']").val();
//     if(!shelf_life){ alert('保质期不能为空');return false;}
    
//     var packaging = $("input[name='packaging']").val();
//     if(!packaging){ alert('包装不能为空');return false;}
//     var origin = $("input[name='origin']").val();
//     if(!origin){ alert('产地不能为空');return false;}
//     var province = $("input[name='province']").val();
//     if(!province){ alert('省份不能为空');return false;}
//     var goods_desc = $("#goods_desc").val();
//     if(!goods_desc){ alert('详细描述不能为空');return false;}
//     var goods_desc_img = $("#goods_desc_img").val();
//     if(!goods_desc_img){ alert('详情图不能为空');return false;}
    var original_img = $("#original_img").val();
    if(!original_img){ alert('商品头图不能为空');return false;}
    var goods_img = $("input[name='goods_img']").val();
    if(!goods_img){ alert('商品缩略图不能为空');return false;}
    
});

$('#uploadfile_goods_desc_img').click(function() {
        $('#goods_desc_img').trigger('click');
  });
var inputElement = document.getElementById("goods_desc_img");
inputElement.addEventListener("change", goods_desc_img_handleFiles, false);
function goods_desc_img_handleFiles(){
    var fileList = this.files;
    var fileStr = '';
    var dd = document.getElementById('content_goods_desc_img');
    dd.innerHTML = '';
    var countImg = 1;
    for( var i = 0 ; i < fileList.length ; i++ ){
  	  var fileList = this.files;
      var reader = new FileReader();
      reader.readAsDataURL(fileList[i]);
      reader.onload = function(e) {
          var image = new Image();
          image.src = e.target.result;
          image.onload=function(){
              if(image.width < 828 ){  // || image.height < 414
            	  alert('第 '+(countImg++)+' 张图片宽高错误');
            	  fileList[i] = '';
              } else {
            	  //var url =window.URL.createObjectURL(fileList.item(i));
            	  dd.innerHTML += "<div class='zero-clipboard' style='width: 9.3em;float: left;'></div><div class='highlight' style='width: 9.3em;display: inline;float: left;'><span><img src='"+image.src+"' width='120px' height='120px'/></span></div>";
              }
          }
      }
    }
}

$('#uploadfile_original_img').click(function() {
        $('#original_img').trigger('click');
});
var inputElement = document.getElementById("original_img");
inputElement.addEventListener("change", original_img_handleFiles, false);
function original_img_handleFiles(){
  var fileList = this.files;
  var fileStr = '';
  console.log(fileList.path);
  var dd = document.getElementById('content_original_img');
  dd.innerHTML = '';
  var countImg = 1;
  for( var i = 0 ; i < fileList.length ; i++ ){
  	  var fileList = this.files;
      var reader = new FileReader();
      reader.readAsDataURL(fileList[i]);
      reader.onload = function(e) {
          var image = new Image();
          image.src = e.target.result;
          image.onload=function(){
              if(image.width < 828 || image.height < 414){
            	  alert('第 '+(countImg++)+' 张图片宽高错误');
            	  fileList[i] = '';
              } else {
                //var url =window.URL.createObjectURL(fileList.item(i));
                dd.innerHTML += "<div class='zero-clipboard' style='width: 9.3em;float: left;'></div><div class='highlight' style='width: 9.3em;display: inline;float: left;'><span><img src='"+image.src+"' width='120px' height='120px'/></span></div>";
              }
          }
      }
    }
}

$("#up").change(function(){
    var fileList = this.files;
    var reader = new FileReader();
    reader.readAsDataURL(fileList[0]);
    reader.onload = function(e) {
        var image = new Image();
        image.src = e.target.result;
        image.onload=function(){
            if(image.width < 190*2 || image.height < 194*2){
                alert('图片宽高：'+image.width+'---'+image.height);
                $("#up").val('');  
                $('#ImgPr').attr('src','');
                fileList = null;
                image = null;
            } else {
                $('#ImgPr').attr('src',image.src);
            }
        }
    } 
});

$(function () {
    $("#IMG_PATH").uploadPreview({ Img: "ImgPr", Width: 120, Height: 120 });
});

$(function(){
  $('.roles-number').blur(function() { 
    var str = $(this).val(); 
    str = $.trim(str);
    if(str < 0) {
        $(this).val(0); 
    }
  });

    $('#dropdownMenu1').typeahead({
        source: <?php echo $this->typeCH; ?>
    });

    $('#dropdownMenu1').keyup(function(){
        $('#dropdown').addClass('hidden');
    })

    $('#dropdownMenu1').click(function(){
        $('#dropdown').removeClass('hidden');
    })

    $('#dropdown li a').click(function(){
        var goodId = $(this).attr('data-id'),
            goodName = $(this).text();
        $("input[name='goods_type']").val(goodId);
        $('#dropdownMenu1').val(goodName);
        $('#dropdown').addClass('hidden');
    })

    $('#dropdownMenu1').change(function(){
        var id = $("input[name='goods_type']").val();
        if(id != '' || id != undefined){
            $("input[name='goods_type']").val('');
        }
        var goodName = $(this).val();
        console.log(goodName);
        var goodList = <?php echo $this->goodList; ?>;
        console.log(goodList);
        for(var i = 0; i < goodList.length; i++){
            if(goodList[i].name == goodName){
                $("input[name='goods_type']").val(goodList[i].id);
            }
        }
    })


    $('#dropdownMenu2').typeahead({
        source: <?php echo $this->brandCH; ?>
    });

    $('#dropdownMenu2').keyup(function(){
        $('#dropdown1').addClass('hidden');
    })

    $('#dropdownMenu2').click(function(){
        $('#dropdown1').removeClass('hidden');
    })

    $('#dropdownMenu2').change(function(){
        var id = $("input[name='brand_id']").val();
        if(id != '' || id != undefined){
            $("input[name='brand_id']").val('')
        }
        var brandName = $(this).val();
        console.log(brandName)
        var brandList = <?php echo $this->brandList; ?>;
        console.log(brandList)
        for(var i = 0; i < brandList.length; i++){
            if(brandList[i].name == brandName){
                $("input[name='brand_id']").val(brandList[i].id);
            }
        }
    })

    $('#dropdown1 li a').click(function(){
        var brandId = $(this).attr('data-id'),
            brandName = $(this).text();
        $("input[name='brand_id']").val(brandId);
        $('#dropdownMenu2').val(brandName);
        $('#dropdown1').addClass('hidden');
    })
});
</script>