<nav class="col-md-2 hidden-print dev-sidebar">
    <?php include(dirname(__FILE__) . '/../sys/dev_nav.phtml')?>
</nav>
<style>
	.s{color:red;}
</style>
<div class="col-md-10">
    <ol class="breadcrumb">
      <li><a href="#">商品管理</a></li>
      <li class="active">编辑列表</li>
    </ol>
    <ul class="nav nav-pills">
      <li role="presentation"><a href="list">商品列表</a></li>
      <li role="presentation" class="active"><a href="#">编辑商品</a></li>
      <li role="presentation"><a href="add">添加商品</a></li>
    </ul>
    <br>
	<?php
		if ($this->errors != '') {
			echo "<div class='alert alert-danger alert-dismissible' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button><strong>{$this->errors}</strong></div>";
		}
	?>
    <br>
    <?php include(dirname(__FILE__) . '/form_update_goods.phtml')?>
</div>