<nav class="col-md-2 hidden-print dev-sidebar">
    <?php include(dirname(__FILE__) . '/../sys/dev_nav.phtml')?>
</nav>
<script src="/js/thumbnails.js" type="text/javascript"></script>
<script src="/laydate/laydate.js" type="text/javascript"></script>
<script>
    laydate.skin('danlan')
</script>
<style>
th {text-align: center;}
td>div{width:29%;float:left;padding:0.3em}
td>input{width:12%;}
</style>
<div class="col-md-10">
    <ol class="breadcrumb">
      <li><a href="#">经销商统计</a></li>
      <li class="active">商品统计</li>
    </ol>
    <form action="" id='ajaxformhaha' method="get">
        <table class="table" style="background:#f5f5f5">
            <tr>
                <td>
                    <div class='input-group col-md-7' style='float: left'>
                        <div class="input-group">
                            <div class="input-group-addon">时间</div>
                            <input class='form-control' style='width:50%;display: inline' type="text" placeholder="开始时间" onclick="laydate()" name="ktime" id='ktime' value='<?=$this->get['ktime']?>'>
                            <input class='form-control' style='width:50%;display: inline' name="gtime" id='gtime' type="text" placeholder="结束时间" onclick="laydate()" value='<?=$this->get['gtime']?>'>
                        </div>
                    </div>
                    <div class="input-group col-md-3">
                        <div class="input-group-addon">品类</div>
                        <select name="goods_type" class="form-control">
                            <option value="0">请选择</option>
                            <?php foreach($this->get_goods_type as $gv){ ?>
                                <option value="<?php echo $gv['id']; ?>" <?= ($this->get['goods_type'] == $gv['id']) ? 'selected=selected' :'' ?> ><?php echo $gv['name']; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                    <div class="input-group col-md-10">
                        <div class="input-group-addon">品牌</div>
                        <select name="brand" class="form-control">
                            <option value="0">请选择</option>
                            <?php foreach($this->getBrand as $bv){ ?>
                                <option value="<?php echo $bv['id']; ?>" <?= ($this->get['brand'] == $bv['id']) ? 'selected=selected' :'' ?>><?php echo $bv['name']; ?></option>
                            <?php } ?>
                        </select>
                        <div class="input-group-addon">搜索商品</div>
                        <input type="text" class="form-control" style="width: 15em;" placeholder="商品名称" name="goods_name" value="<?= $this->get['goods_name']; ?>">
                    </div>
                    </div>
                    <span style='float:right;padding:0.3em'>
                        <input class="btn btn-primary" type="submit" value="搜索">
                        <bottom class="btn btn-primary export" style='width:8em'>导出数据</bottom>
                    </span>
                </td>
            </tr>
        </table>
    </form>
    <table class="table table-hover" style="text-align: center;">
    <caption></caption>
    <thead>
        <tr>
            <th>品类</th>
            <th>品牌</th>
            <th>商品名称</th>
            <th>活动情况</th>
            <th><span onclick="sort('goods_number','<?= !isset($_GET['goods_number']) ? 'desc' : ($_GET['goods_number'] == 'desc' ? 'asc' : 'desc') ?>')">销售数量<span class='glyphicon glyphicon-chevron-<?=($_GET['goods_number'] == 'desc') ? 'up':'down'?>' style='top: 4px;'></span></span></th></th>
            <th>属性(正常/赠品）</th>
        </tr>
    </thead>
      <tbody>
        <?php if ($this->developer): ?>
        <?php foreach ($this->developer as $info): ?>
            <tr>
                <td class='col-md-1'><?=$info['name']?></td>
                <td class="col-md-1"><?=$info['brand']; ?></td>
                <td class='col-md-1'><?=$info['goods_name']?></td>
                <td class="col-md-1"><?php if($info['type']==1){
                        echo "买就送";
                    }elseif($info['type']==2){
                        echo "限时活动";
                    }elseif($info['type']==3){
                        echo "品牌活动";
                    }else{
                        echo "无";
                    } ?></td>
                <td class="col-md-1"><?=$info['goods_number']; ?></td>
                <td class="col-md-1"><?=($info['is_activitygifts'])?赠品:正常 ?></td>
            </tr>
        <?php endforeach; ?>
        <?php endif; ?>
      </tbody>
    </table>
    <?php echo $this->paglist; ?>
</div>

<script>
    $(document).on('click','.export',function(){
        if (confirm("你确定要导出商品数据信息吗？")) {
            window.location.href="/distributor/goodsExport?"+$("form").serialize();
        }
    });
    function sort(name, state)
    {
        if (name == 'goods_number') {
            if (<?= $this->get['goods_number'] ? 'true' : 'false' ?> == false) {
                window.location.href="goodsstatistics?"+$("#ajaxformhaha").serialize()+'&goods_number='+state;
            } else {
                window.location.href="goodsstatistics?"+$("#ajaxformhaha").serialize()+'&goods_number='+state;
            }
        }
    }
</script>
