<script src="/laydate/laydate.js" type="text/javascript"></script>
<nav class="col-md-2 hidden-print dev-sidebar">
    <?php include(dirname(__FILE__) . '/../sys/dev_nav.phtml')?>
</nav>
<style>
.current{color:#000000;}
th {text-align: center;}
a {cursor: pointer;}
</style>
<script>
    laydate.skin('danlan')
</script>
<div class="col-md-10">
    <ol class="breadcrumb">
      <li><a href="JavaScript:void(0)">消息管理</a></li>
      <li class="active">系统消息列表</li>
    </ol>
    <div class="ctrls list-content">
        <form method="get">
            <table class="table" style="background:#f5f5f5">
                <tr>
                    <td>
                        <div class="input-group col-md-3" style='float:left'>
                            <div class="input-group-addon">消息类型</div>
                            <select name='type' class='form-control'>
                                <option value=''>请选择</option>
                                <option value='1' <?=($this->get['type'] == '1')? 'selected' : ''?>>订单消息</option>
                                <option value='2' <?=($this->get['type'] == '2')? 'selected' : ''?>>账单消息</option>
                                <option value='3' <?=($this->get['type'] == '3')? 'selected' : ''?>>官方消息</option>
                            </select>
                        </div>
                        <div class='input-group col-md-5' style='float: left'>
                            <div class="input-group">
                                <div class="input-group-addon">时间</div>
                                <input class='form-control' style='width:50%;display: inline' type="text" placeholder="开始时间" onclick="laydate()" name="ktime" id='ktime' value='<?=$this->get['ktime']?>'>
                                <input class='form-control' style='width:50%;display: inline' name="gtime" id='gtime' type="text" placeholder="结束时间" onclick="laydate()" value='<?=$this->get['gtime']?>'>
                            </div>
                        </div>
                    </td>
                    <td><input type="submit" class='btn btn-primary' value="搜索"></td>
                </tr>
            </table>
        </form>
    </div>
    <ul class="nav nav-pills">
      <li role="presentation" class="active"><a href="#">系统消息列表</a></li>
      <li role="presentation"><a href="/message/add">发送系统消息</a></li>
    </ul>
    <br>
    <br>
    <div class="table-wrapper products-table section mt-20">
        <div class="row">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th class="col-xs-2">标题</th>
                    <th class="col-md-4">消息内容</th>
                    <th class="col-md-1">消息类型</th>
                    <th class="col-md-2">创建时间</th>
                    <th class="col-md-2">操作</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($this->list as $key=>$val) { ?>
                    <tr id="brand<?= $val['id']; ?>">
                        <td class='text-center'><?= $val['title']; ?></td>
                        <td class='text-center'><?= $val['content']?></td>
                        <td class='text-center'><?= ($val['type'] == 1)?'订单消息':($val['type'] == 2 ? '账单消息':($val['type'] == 3 || $val['type'] == 4 ? '官方消息':'')) ?></td>
                        <td class='text-center'><?= date('Y-m-d H:i', $val['create_time'])?></td>
                        <td class='text-center'>
                            <ul class='list-inline'>
                                <li class="last">
                                    <a href='update?id=<?=$val['id']?>'>编辑</a>
                                    <?php if ($this->rbac == '*' ? true :(in_array('message_resend', $this->rbac['action']))) :?>
                                        <a onclick="if(confirm('确定要从新发送消息吗？')==false)return false; resend(<?=$val['id']?>)">重新发送</a>
                                    <?php endif;?>
                                    <?php if ($this->rbac == '*' ? true :(in_array('message_del', $this->rbac['action']))) :?>
                                        <a onclick="if(confirm('您确定要删除吗？')==false)return false; del(<?=$val['id']?>,<?=$val['type']?>)">删除</a>
                                    <?php endif;?>
                                </li>
                            </ul>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
        <?=$this->paglist?>
    </div>
</div>

<script type="text/javascript">
function resend(id)
{
    $.ajax({
       type: "POST",
       url: "resend",
       dataType: "json",
       data: "id="+id,
       success: function(data) {
           if (data == 200) {
        	   alert('发送成功');
           } else if (data == 400) {
        	   alert('发送失败');
           }
       }
    });
}

function del(id,type)
{
    $.ajax({
     type: "POST",
     url: "del",
     dataType: "json",
     data: 'id='+id+'&type='+type,
     success: function(data){
       if (data == 200) {
         $("#brand"+id).remove();
         $("#modal").append('<div class="col-md-3"></div><div class="col-md-6" style="margin-top: 60px"><div class="alert alert-success" role="alert"><p>删除成功</p></div></div><div class="col-md-3"></div>');
         setTimeout(function(){$("#modal").modal("hide")},2000);
       }
       if (data == 400) {
         alert('请重试');
       }
     }
  });
}
</script>