<script src="/js/thumbnails.js" type="text/javascript"></script>
<nav class="col-md-2 hidden-print dev-sidebar">
    <?php include(dirname(__FILE__) . '/../sys/dev_nav.phtml')?>
</nav>
<style>
.s{color:red;}
th {text-align: center;}
</style>

<div class="col-md-10">
    <ol class="breadcrumb">
      <li><a href="messageList">系统消息列表</a></li>
      <li class="active">发送系统消息</li>
    </ol>
    <ul class="nav nav-pills">
      <li role="presentation"><a href="messageList">系统消息列表</a></li>
      <li role="presentation" class="active"><a href="javascript:void(0)">发送系统消息</a></li>
    </ul>
    <br>
    <?php
      if ($this->errors != '') {
        echo "<div class='alert alert-danger alert-dismissible' role='alert'>
          <button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
      <strong>{$this->errors}</strong>
        </div>";
      }
    ?>
    <br>
    <br>
    <div class="tab-content">
        <form action='update' method="POST" enctype="multipart/form-data" class="form-horizontal col-sm-12">
            <input type='hidden' name='id' value='<?=$this->info['id']?>'>
            <div class="form-group col-sm-12">
                <label class="col-sm-2 control-label" for="Bingtuan_goodsName">标题<span class='s'> *</span></label>
                <div class="col-sm-3">
                    <input type="text" class="form-control" name='title' value='<?=$this->info['title']?>'><span></span>
                </div>
            </div>
              <div class="form-group col-sm-12">
                <label class="col-sm-2 control-label">内容<span class='s'> *</span></label>
                <div class="col-sm-5">
                  <textarea class="form-control" name='content' rows="4" cols='4'><?=$this->info['content']?></textarea>
                </div>
              </div>    
              <div class="form-group col-sm-12">
                <label class="col-sm-2 control-label">发送用户<span class='s'> *</span></label>
                <div class="col-sm-5">             
                  <select id="disabledSelect" style="width:8em" class="form-control" name='receiver'>
                      <option value='0'>全部人</option>
                      <option value='1' <?= ($this->info['receiver']==1)?'selected = "selected"':'' ?>>普通用户</option>
                      <option value='2' <?= ($this->info['receiver']==2)?'selected = "selected"':'' ?>>大客户</option>
                  </select>
                </div>
              </div>
              <div class="form-group col-sm-12">
                <div class="col-sm-offset-2 col-sm-10">
                  <button type="submit" class="btn btn-success">提交</button>
                </div>
              </div>
        </form>
    </div>
</div>
