<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>商品详情</title>
	<meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<link rel="stylesheet" type="text/css" href="/css/swiper.min.css" />
	<link rel="stylesheet" href="/vendor/bootstrap/v3/css/bs-col-sys.min.css" />
	<link rel="stylesheet" type="text/css" href="/vendor/css/ratchet.min.css" />
	<link rel="stylesheet" type="text/css" href="/css/app.css">
	<link rel="stylesheet" type="text/css" href="/css/mycss.css" />
	<script type="text/javascript" src="/js/jquery-1.8.3.min.js"></script>
	<script type="text/javascript" src="/js/function.js"></script>
	<script type="text/javascript" src="/js/baidu_count.js"></script>
</head>
<body>
<div class="contbody pb140">
	<header class="bar bar-nav bg-bule b-n">
		<a href="javascript:;" onclick="javascript:history.go(-1);" class="icon icon-goback pull-left"></a>
		<h1 class="title c-white">商品详情</h1>
	</header>
	<div class="swiper-container mt-56">
		<div class="swiper-wrapper">
	       	<?php for($i=0;$i<count($info["images"]);$i++){?>
			  <div class="swiper-slide"><img src="<?=$info['images'][$i]?>" /></div>
			 <?php }?>
		</div>
		<div class="swiper-pagination"></div>
	</div>
	
	<div class="product_info">
		<dl class="productdl product_info_dl clearfix">
			<dt><?=$info['goods_name']?></dt>
			<dd><span class="redfont">￥<?php if(!empty($info['activity_goods'])){if($info['activity_goods']['type']==1){echo $info['all_price'];}else if($info['activity_goods']['type']==2|| $info['activity_goods']['type']==3){echo $info['activity_goods']['activity_price'];}}else{echo $info['all_price'];}?></span><span class="grayfont">￥<?=$info['city_price']?></span></dd>
			<?php if(!empty($info['activity_goods'])){?>
			<dd class="clearfix"><span class="redbg fl"><?php if(!empty($info['activity_goods']['name'])){echo $info['activity_goods']['name'];}else{echo "";}?></span><p class="sendtips fl"><?php if($info['activity_goods']['type']==2){$info['activity_goods']['gifts_list']['goods_thumb'];}?><span><?php if($info['activity_goods']['type']==1) echo $info['activity_goods']['gifts_list']['goods_name'];?></span></p></dd>
		   <?php }?>
		</dl>
	</div>
	
	<div class="product_info mt10">
		<p class="payNavtit">产品参数</p>
		<ul class="pro_parameterul">
		<?php if(!empty($info['name'])){ ?>
			<li><span class="parame_name fl">品牌</span><span class="parame_txt fl"><?=$info['name']?></span></li>
		<?php }?>
		<?php if(!empty($info['goods_name'])){ ?>
			<li><span class="parame_name fl">品名</span><span class="parame_txt fl"><?=$info['goods_name']?></span></li>
		<?php }?>
		<?php if(!empty($info['goods_unit'])){ ?>
			<li><span class="parame_name fl">单位</span><span class="parame_txt fl"><?=$info['goods_unit']?></span></li>
		<?php }?>
		<?php if(!empty($info['standard'])){ ?>
			<li><span class="parame_name fl">规格</span><span class="parame_txt fl"><?=$info['standard']?></span></li>
		<?php }?>
		<?php if(!empty($info['production_time'])){ ?>
			<li><span class="parame_name fl">生产日期</span><span class="parame_txt fl"><?= date("Y-m-d",$info['production_time'])?></span></li>
		<?php }?>
		<?php if(!empty($info['storage'])){ ?>
			<li><span class="parame_name fl">贮存条件</span><span class="parame_txt fl"><?=$info['storage']?></span></li>
		<?php }?>
		<?php if(!empty($info['shelf_life'])){ ?>
			<li><span class="parame_name fl">保质期</span><span class="parame_txt fl"><?=$info['shelf_life']?></span></li>
		<?php }?>
		<?php if(!empty($info['origin'])){ ?>
			<li><span class="parame_name fl">产地</span><span class="parame_txt fl"><?=$info['origin']?></span></li>
		<?php }?>
		<?php if(!empty($info['province'])){ ?>
			<li><span class="parame_name fl">省份</span><span class="parame_txt fl"><?=$info['province']?></span></li>
		<?php }?>
		<?php if(!empty($info['packaging'])){ ?>
			<li><span class="parame_name fl">包装方式</span><span class="parame_txt fl"><?=$info['packaging']?></span></li>
		<?php }?>
		<?php if(!empty($info['goods_weight'])){ ?>
			<li><span class="parame_name fl">净重</span><span class="parame_txt fl"><?=$info['goods_weight']?></span></li>
		<?php }?>
		</ul>
	</div>
	<div class="toogle-goods">
       <p class='carts'>点击收起商品<span class="icon icon-top-cart"></span></p>
    </div>
	<div class="product_info mt10">
		<p class="payNavtit">图文详情</p>
		<div class="product_infodeataildiv">
			<p class="detailpro"><?=$info['goods_desc']?></p>
			<?php for($i=0;$i<count($info['goods_desc_images']);$i++){?>
			     <img src="<?=$info['goods_desc_images'][$i]?>" />
			<?php }?>
		</div>
	</div>
</div>
<div class="bottomprice product_order_price">
	<div class="bottompricediv">
		<dl class="bottompricedl fl">
			<dt>单价 :  <span class="redfont"><?=$info['all_price']?></span>元</dt>
		</dl>
		<span class="bottompricebtn fr">购买</span>
		<input type="hidden" id="goods_id" name="goods_id" value="<?=$info['goods_id'] ?>">
		<input type="hidden" id="goods_name" name="goods_name" value="<?=$info['goods_name'] ?>">
		<input type="hidden" id="all_price" name="goods_price" value="<?=$info['all_price']?>">
		<input type="hidden" id="city_price" name="city_price" value="<?=$info['city_price']?>">
		<input type="hidden" id="goods_thumb" name="goods_thumb" value="<?=$info['goods_thumb']?>">
		<input type="hidden" id="goods_unit" name="goods_unit" value="<?=$info['goods_unit']?>">
		<input type="hidden" id="amount" name="amount" value="<?=$info['amount']?>"
		<input type="hidden" id="receiving_num" name="<?=$info['activity_goods']['free_num']?>" value="<?=$info['activity_goods']['receiving_num']?>">
		<?php if(isset($info['activity_goods']) && isset($info['activity_goods']['type'])){?>
		<?php if($info['activity_goods']['type']==1){?>
		   <input type="hidden" id="activity_goods_name" name="activity_goods_name" value="<?=$info['activity_goods']['gifts_list']['goods_name']?>">
		<?php }}?>
		<input type="hidden" id="type" name="type" value="<?php if(isset($info['activity_goods']['type'])){echo $info['activity_goods']['type'];}?>">
		<input type="hidden" id="activity_id" name="activity_id" value="<?php if(isset($info['activity_goods']['activity_id'])){echo $info['activity_goods']['activity_id'];}?>">
	</div>
</div>
<script type="text/javascript" src="/js/swiper.min.js"></script>
<script>
var swiper = new Swiper('.swiper-container', {
	pagination: '.swiper-pagination',
	paginationClickable: false,
	autoplay: 3000
});
$('.bottompricebtn').click(function(){
	var all_price = $(this).siblings('#city_price').attr('value');//
	var price= $(this).siblings("#all_price").attr('value');//
	var names = $(this).siblings("#goods_name").attr('value');
	var num = 1;
	var val=1;
	var type = $(this).siblings("#type").attr('value');//
	var goods_id = $(this).siblings("#goods_id").attr('value');//
	var activity_id=$(this).siblings('#activity_id').attr('value');//
	if(activity_id!=''){activity_id=activity_id;}else{activity_id=0;};
	var imgadd=$(this).siblings('#goods_thumb').attr('value');//市场数量
	var unit=$(this).siblings('#goods_unit').attr('value');//规格
	var receiving_num=$(this).siblings('#receiving_num').attr('value');//买送数量
	var free_num=$(this).siblings('#receiving_num').attr('name');//买送数量
	var actign=$(this).siblings('#activity_goods_name').attr('value');//活动商品名称
	var amount=$(this).siblings('#amount').attr('value');//活动商品名称
 	var info={'free_num':free_num,'receiving_num':receiving_num,'type_h':0,'state':'1','names':names,'count':num,'id':goods_id,'price':price,'imgadd':imgadd,'unit':unit,'all_price':all_price,'type':type,'activityId':activity_id,'amount':amount,'actign':actign};

	$.ajax({
		type:'POST',
		url:"/goods/getinfo",
		//dataType : 'josn',
		data:{'info':info},
	    success:function(data){
    	obj=eval("("+data+")");
        if(obj.code==1){
        	window.location.href = '/cart/index?goods_id='+obj.goods_id+"&activity_goods="+obj.activity_goods;
	    }else{
	    	alert('购买失败');
		}   
		}
	});
})
//商品参数隐藏和显示
$(document).ready(function(){
	$(".pro_parameterul li").hide();
    var flag=1;
    for(var i=0;i<4;i++){
    	$($(".pro_parameterul li")[i]).show();
	}
    var liList=$(".pro_parameterul li").length;
    if(liList<4){
        return false;
     }
    var start=liList-4;
	$(this).find('.carts').html('点击显示全部<span class="icon icon-down-cart "></span>');
	$(".toogle-goods").click(function(){
		num = start;
		if(flag){
		   for(var i=num;i<=liList;i++){
				$($(this).parent().find('.pro_parameterul li')[i]).show();
				$(this).find('.carts').html('点击收起全部<span class="icon  icon-top-cart"></span>');
			}
		   flag=0;
		}else{
	        for(var i=num+1;i<liList;i++){
	        	$($(".pro_parameterul li")[i]).hide();
	    	}
	        $(this).find('.carts').html('点击显示全部<span class="icon icon-down-cart "></span>');
	        flag=1;
		}
	})
})
</script>
</body>
</html>