<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>注册协议</title>
	<meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<link rel="stylesheet" href="/vendor/bootstrap/v3/css/bs-col-sys.min.css" />
	<link rel="stylesheet" type="text/css" href="/vendor/css/ratchet.min.css" />
	<link rel="stylesheet" type="text/css" href="/css/app.css">
	<script type="text/javascript" src="/js/jquery-1.8.3.min.js"></script>
	<script type="text/javascript" src="/js/swiper.min.js"></script>
	<script type="text/javascript" src="/js/function.js"></script>
        <script type="text/javascript" src="/js/baidu_count.js"></script>
</head>
	<header class="bar bar-nav bg-bule b-n">
		<h1 class="title c-white">注册</h1>
	</header>
	<div class="content content-box mb-110 bg-gray2" style="padding-top: 40px;" >
		<article>
			<h3 class="a-title text-center mb-30 mt-30">冰团e购《用户注册协议》</h3>
			    <p class="part pl-0 mt-10 mb-10">　　本协议为您与“冰团e购”管理者之间所订立的契约，具有合同的法律效力，请您务必仔细阅读和理解本《用户注册协议》（以下简称《协议》）中规定的所有权利和限制。除非您接受本《协议》条款，否则您无权注册、登录或使用本协议所涉及的相关服务。您一旦注册、登录、使用或以任何方式使用本《协议》所涉及的相关服务的行为将视为对本《协议》的接受，即表示您同意接受本《协议》各项条款的约束。如果您不同意本《协议》中的条款，请不要注册、登录或使用本《协议》相关服务。</p>
				<p class="part">1. 服务内容</p>
				<ul class="pl-0 mt-10 mb-10">
					<li>　　1.1:“冰团e购“是为厂家提供品牌宣传、产品推广、渠道建设同时也为终端店提供冷食货源的线上采购平台。</li>
				    <li>　　1.2 您一旦注册成功成为用户，您将得到一个密码和帐号，您需要对自己在帐户中的所有活动和事件负全责。如果由于您的过失导致您的帐号和密码脱离您的控制，则由此导致的针对您、或任何第三方造成的损害，您将承担全部责任。</li>
                    <li>　　1.3 用户理解并接受，冰团e购仅提供相关的网络服务，除此之外与相关网络服务有关的设备（如个人电脑、手机、及其他与接入互联网或移动互联网有关的装置）及所需的费用（如为接入互联网而支付的电话费及上网费、为使用移动网而支付的手机费）均应由用户自行负担。</li>
				</ul>
				<p class="part">2. 用户使用规则</p>
				<ul class="pl-0 mt-10 mb-10">
                    <li>　　2.1 用户在申请使用冰团e购时，必须提供准确的个人资料，如个人资料有任何变动，必须及时更新。因用户提供个人资料不准确、不真实而引发的一切后果由用户承担。</li>
                    <li>　　2.2 用户应妥善保存帐号、密码，避免以任何脱离用户控制的形式交由他人使用。如用户发现其帐号遭他人非法使用，应立即通知冰团e购。因黑客行为或用户的保管疏忽导致帐号、密码遭他人非法使用，冰团e购不承担任何责任。</li>
                    <li>　　2.3 用户应当为自身注册帐户下的一切行为负责，因用户行为而导致的用户自身或其他任何第三方的任何损失或损害，冰团e购不承担责任。</li>
                    <li>　　2.4 用户理解并接受冰团e购提供的服务中可能包括冷食产品广告，用户同意在使用过程中显示冰团e购合作伙伴提供的广告。
                    <li>　　2.5 用户在使用冰团e购服务过程中，必须遵循以下原则：</li>
                    <li>　　2.5.1 遵守中国有关的法律和法规；</li>
                    <li>　　2.5.2 遵守所有与网络服务有关的网络协议、规定和程序；</li>
                    <li>　　2.5.3不得侵犯冰团e购和其他任何第三方的专利权、著作权、商标权、名誉权或其他任何合法权益；</li>
                    <li>　　2.5.4不得利用冰团e购进行任何不利于冰团e购的行为；</li>
                    <li>　　2.5.5如发现任何非法使用用户帐号或帐号出现安全漏洞的情况，应立即通告冰团e购。</li>
                    <li>　　2.6 如用户在使用网络服务时违反任何上述规定，冰团e购或其授权的人有权要求用户改正或直接采取一切必要的措施（包括但不限于更改或删除用户收藏的内容等、暂停或终止用户使用网络服务的权利）以减轻用户不当行为造成的影响。</li>
				</ul>
				<p class="part">3. 服务变更、中断或终止</p>
				<ul class="pl-0 mt-10 mb-10">
                    <li>　　3.1 鉴于网络服务的特殊性，用户同意冰团e购有权根据业务发展情况随时变更、中断或终止部分或全部的网络服务而无需通知用户，也无需对任何用户或任何第三方承担任何责任；</li>
                    <li>　　3.2 用户理解，冰团e购需要定期或不定期地对提供网络服务的平台（如互联网网站、移动网络等）或相关的设备进行检修或者维护，如因此类情况而造成网络服务在合理时间内的中断，冰团e购无需为此承担任何责任，但冰团e购应尽可能事先进行通告。</li>
                    <li>　　3.3 如发生下列任何一种情形，冰团e购有权随时中断或终止向用户提供服务而无需对用户或任何第三方承担任何责任：
                    <li>　　3.3.1 用户提供的个人资料不真实；</li>
                    <li>　　3.3.2 用户违反本《协议》中规定的使用规则。</li>
                </ul>
                <p class="part">4.知识产权</p>
				<ul class="pl-0 mt-10 mb-10">
                    <li>　　4.1 冰团e购的任何文本、图片、图形均受版权、商标和/或其它财产所有权法律的保护，未经相关权利人同意，上述资料均不得用于任何商业目的。</li>
                </ul>
                <p class="part">5.隐私保护</p>
				<ul class="pl-0 mt-10 mb-10">
                    <li>　　5.1 保护用户隐私是冰团e购的一项基本政策，冰团e购保证不对外公开或向第三方提供单个用户的注册资料，但下列情况除外：</li>
                    <li>　　5.1.1 事先获得用户的明确授权；</li>
                    <li>　　5.1.2 根据有关的法律法规要求；</li>
                    <li>　　5.1.3 按照相关政府主管部门的要求；</li>
                    <li>　　5.1.4 为维护社会公众的利益；</li>
                    <li>　　5.1.5 为维护冰团e购的合法权益。</li>
                    <li>　　5.2 在不透露单个用户隐私资料的前提下，冰团e购有权对整个用户数据库进行分析并对用户数据库进行商业上的利用。</li>
                </ul>
                <p class="part">6.免责声明</p>
				<ul class="pl-0 mt-10 mb-10">
                    <li>　　6.1 对于因互联网网络故障、计算机故障或病毒、信息损坏或丢失、计算机系统问题或其它任何不可抗力原因而产生损失，冰团e购不承担任何责任，但将尽力减少因此而给用户造成的损失和影响。</li>
                </ul>
                <p class="part">7.法律及争议解决</p>
				<ul class="pl-0 mt-10 mb-10">
                    <li>　　7.1 本协议适用中华人民共和国法律。</li>
                    <li>　　7.2 因本协议引起的或与本协议有关的任何争议，各方应友好协商解决；协商不成的，任何一方均可将有关争议提交至北京仲裁委员会并按照其届时有效的仲裁规则仲裁；仲裁裁决是终局的，对各方均有约束力</li>
                </ul>
                <p class="part">8.其他条款</p>
				<ul class="pl-0 mt-10 mb-10">
                     <li>　　8.1 如果本协议中的任何条款无论因何种原因完全或部分无效或不具有执行力，或违反任何适用的法律，则该条款被视为删除，但本协议的其余条款仍应有效并且有约束力。</li>
                     <li>　　8.2冰团e购有权随时根据有关法律、法规的变化以及公司经营状况和经营策略的调整等修改本协议，而无需另行单独通知用户。用户可随时通过网站浏览最新服务协议条款。当发生有关争议时，以最新的协议文本为准。如果不同意冰团e购对本协议相关条款所做的修改，用户有权停止使用网络服务。如果用户继续使用网络服务，则视为用户接受冰团e购对本协议相关条款所做的修改。</li>
                     <li>　　8.3冰团e购在法律允许最大范围对本协议拥有解释权与修改权。</li>
                </ul>
                <p class="part">9.协议生效</p>
　　本协议于用户点击协议生效<br>
　　本协议于用户点击冰团e购注册页面的同意注册并完成注册程序、获得冰团e购账号和密码时生效，对冰团e购和用户均具有约束力。<br>
<p class="text-right">本协议于2016年1月11日发布。</p>
		</article>
	</div>
	<form action="/register/register?qrcode=<?php echo $_GET['qrcode']?>" method="POST">
    	<div class="bar bar-standard bar-footer-secondary content-box xieyibox" style="border-top:1px solid #cecece">
    		<div class="check-box text-center agreecheckjs">
    			<span class="icon icon-check-gray"  id="iagrees"></span>
    			<input type="checkbox" id="iagree"/>我已阅读并同意协议
    		</div>
    	  <button id="xieyi-next" class="btn btn-block button-gray b-n btn-public ">下一步</button>
    	</div>
    </form>
</body>
</html>
    
