<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>用户注册</title>
	<meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
    <script src="/js/jquery-1.8.3.min.js"></script>
	<link rel="stylesheet" href="/vendor/bootstrap/v3/css/bs-col-sys.min.css" />
	<link rel="stylesheet" type="text/css" href="/vendor/css/ratchet.min.css" />
	<link rel="stylesheet" type="text/css" href="/css/app.css">
	<link rel="stylesheet" type="text/css" href="/css/mobile-select-area.css">
	<link rel="stylesheet" type="text/css" href="/css/mycss.css" />
	<script type="text/javascript" src="/js/jquery-1.8.3.min.js"></script>
	<script type="text/javascript" src="/js/function.js"></script>
	<script type="text/javascript" src="/js/dialog.js"></script>
	<script type="text/javascript" src="/js/mobile-select-area.js"></script>
	<script type="text/javascript" src="/js/mobiscroll_date.js" ></script> 
	<script type="text/javascript" src="/js/mobiscroll.js"></script>
	    <script type="text/javascript" src="/js/baidu_count.js"></script>

	<style>
    ::-webkit-input-placeholder { /* WebKit browsers */ 
    color: #000000; 
    } 
    :-moz-placeholder { /* Mozilla Firefox 4 to 18 */ 
    color: #000000; 
    } 
    ::-moz-placeholder { /* Mozilla Firefox 19+ */ 
    color: #000000; 
    } 
    :-ms-input-placeholder { /* Internet Explorer 10+ */ 
    color: #000000; 
    } 
    </style>
</head>
<body class="bg-gray1">
	<header class="bar bar-nav bg-bule b-n">
		
		<h1 class="title c-white">注册</h1>
	</header>
	<div class="form-box container mt-80  ">
		<form action='reginfo?uid=<?php echo $uid;?>' method='post'>
			<div class="input-box mb-25">
				<span class="icon icon-fangz"></span>
				<input class="b-n b-b-1-gray bg-gray1 c-gray pull-right pl-0 w-95" type="text"  name='cname' placeholder="公司名称/单位名称/店铺名称"   value="" />
			</div>
			<div class="input-box clearfix mb-25">
				<span class="icon icon-address"></span>
				<div class="pull-right pl-0 w-95">
		<div  class="add add-province">
								<input type="text" id="txt_area2" class="editliaddressput editliaddressputmax" readonly name="city" value="省份/城市" data-value=""/>
								<input type="hidden" id="hd_area" name="city" value="11,1101,0"/>
			<script class="resources library" src="/js/area.js" type="text/javascript"></script>
			<script>
				var selectArea2 = new MobileSelectArea();
				selectArea2.init({trigger:'#txt_area2',value:$('#txt_area2').data('value'),data:json,eventName:'click'});
			</script>
		
							</div>
		
				</div>
			</div>
			<div class="input-box mb-10 clearfix">
				
				<input class="b-n b-b-c-2-gray bg-gray1 c-gray pull-right pl-0 w-95" type="text"  name='address' placeholder="详细地址"   value="" />
			</div>
			<div class="input-box mb-10 clearfix">
				<span class="icon icon-ren"></span>
				<input class="b-n b-b-1-gray bg-gray1 c-gray pull-right pl-0 w-95" type="text" name='uname'   placeholder="联系人姓名"   value="" />
			</div>
			<div class="input-box mb-10 clearfix">
				<span class="icon icon-phone"></span>
				<input class="b-n b-b-1-gray bg-gray1 c-gray pull-right pl-0 w-95" type="text" name='telphone' placeholder="联系人手机"   value="" />
			</div>
			<div class="input-box mb-45">
				<span class="icon icon-email"></span>
				<input class="b-n b-b-1-gray bg-gray1 c-gray pull-right pl-0 w-95" type="text"  name='email'  placeholder="邮箱"  value="" />
			</div>
			<input type="submit" name='submit'  value="提交审核" class="btn btn-block c-white bg-bule b-n btn-public mb-20 f-n" style="padding: 13px 0">
		</form>
	</div>
</body>
</html>
