<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>用户注册</title>
	<meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<script src="<?=Yaf_Registry::get('weixinurl')?>/js/jquery-1.8.3.min.js"></script>
	<link rel="stylesheet" href="<?=Yaf_Registry::get('weixinurl')?>/vendor/bootstrap/v3/css/bs-col-sys.min.css" />
	<link rel="stylesheet" type="text/css" href="<?=Yaf_Registry::get('weixinurl')?>/vendor/css/ratchet.min.css" />
	<link rel="stylesheet" type="text/css" href="<?=Yaf_Registry::get('weixinurl')?>/css/app.css">
	    <script type="text/javascript" src="/js/baidu_count.js"></script>
<style>
::-webkit-input-placeholder { /* WebKit browsers */ 
color: #000000; 
} 
:-moz-placeholder { /* Mozilla Firefox 4 to 18 */ 
color: #000000; 
} 
::-moz-placeholder { /* Mozilla Firefox 19+ */ 
color: #000000; 
} 
:-ms-input-placeholder { /* Internet Explorer 10+ */ 
color: #000000; 
} 
</style>
</head>
<body class="bg-gray1">
	<header class="bar bar-nav bg-bule b-n">
		<h1 class="title c-white">注册</h1>
	</header>
	<div class="form-box container mt-80  ">
		<form action="/register/register"  method="post" id="form-data">
			<div class="input-box icon-username p-r mb-10 icon-gray-username">
				<input class="c-gray bg-gray1 b-b-c-2-gray " type="text"  id="phone"  name="account"    placeholder="输入手机号码"  value="<?=$this->data['account']?>" />
			</div>
			<div class="input-box yzm p-r mb-10 icon-gray-yun">
				<div class="row">
					<div class="col-xs-6" style="padding-right: 0px;">
						<input class="c-gray bg-gray1 b-b-c-2-gray  mt-10 "  name="vcode"   style="padding-right: 0px;height: 30px;padding-bottom:8px " placeholder="输入验证码"  type="text" value="" />
					</div>
					<div class="col-xs-6">
						<input class="c-gray btn btn-block c-white b-n bg-bule  btn-public mb-15 f-n" id="times" onclick="verifycode()" type="button"  value="发送验证码"  style="letter-spacing: 1px;padding: 11px 0">
					</div>
				</div>
			</div>
			<div class="input-box icon-password p-r mb-10 icon-gray-shuo">
				<input class="c-gray bg-gray1 b-b-c-2-gray " type="password"  name="password"  placeholder="输入新密码"  value="" />
			</div>
			<div class="input-box icon-password p-r mb-20 icon-gray-shuo">
				<input class="c-gray bg-gray1 b-b-c-2-gray " type="password"  name="repassword"  placeholder="确认密码"  value="" />
				<input type="hidden"  name="qrcode"  value="<?php echo $_GET['qrcode'];?>" />
			</div>
			<input type="submit" class="btn btn-block c-white bg-bule2 b-n btn-public mb-20 b-n" name="tijiao" value="提交">
		</form>
	</div>
</body>
<script type="text/javascript">
    $(function(){
        var qrcode = $("input[name='qrcode']").val();
        if(qrcode == ''){
            alert('获取经销商信息失败，请重试!');
            history.go(-1);
        }
    })

function verifycode(){
	 var value=$('#phone').val();
    $.ajax({
      type: "POST",
      url: "vcode",
      dataType: "json",
      data: "phone="+value,
       success: function(data){
    	   if(data.success==0){
    		   alert(data.error);
      		}else{
      			settime();
            }
       }
   	 });
}
var countdown=60; 
function settime(){
	    if (countdown == 0) { 
	        $('#times').removeAttr("disabled");    
	        $('#times').attr("value","重新发送验证码"); 
	        countdown = 60; 
	        return;
	    } else { 
	    	$('#times').attr("disabled", true); 
	    	$('#times').attr("value","重新发送(" + countdown + ")"); 
	        countdown--; 
	    } 
	    setTimeout("settime()" ,1000);
}
$(document).on('submit','#form-data',function(){
    var account = $("input[name='account' ]").val();
    if(!account){ alert('手机号不能为空');return false;}
    var vcode = $("input[name='vcode']").val();
    if(!vcode){ alert('验证码不能为空');return false;}
    var password = $("input[name='password' ]").val();
    if(!password){ alert('密码不能为空');return false;}
    var repassword = $("input[name='repassword']").val();
    if(!repassword){ alert('请输入第二次密码');return false;}
    if(repassword!=password){ alert('两次密码输入不一致');return false;}
})
</script>
</html>
