<script src="/laydate/laydate.js" type="text/javascript"></script>
<nav class="col-md-2 hidden-print dev-sidebar">
    <?php include(dirname(__FILE__) . '/../sys/dev_nav.phtml')?>
</nav>
<style>
th {text-align: center;}
.table>tbody>tr>td>.input-group {float: left;padding: 0.2em;width:20%}
</style>

<div class="col-md-10">
    <ol class="breadcrumb">
      <li><a href="javascript:void(0)">优惠券管理</a></li>
      <li class="active">优惠券列表</li>
    </ol>
    <div>
        <form action="" method="get" id='ajaxform'>
        <table class="table" style="background:#f5f5f5">
            <tr>
                <td>
                    <div class="input-group" style='width: 18em'>
                        <div class="input-group-addon">公司</div>
                        <select name="company_id" class='form-control' id='company_id'>
                            <option value="0">全部</option>
                            <?php foreach($this->getCompanyList as $k => $v){ ?>
                                    <option value="<?=$v['id']?>" <?= ($this->get['company_id'] == $v['id']) ? 'selected=selected' :'' ?>><?= $v['name']; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                    <div class="input-group" style='width: 21em'>
                        <div class="input-group-addon">时间</div>
                        <input type="text" class='form-control' style='width: 8em;' placeholder="开始时间" onclick="laydate()" name="ktime" id='ktime' value='<?=$this->get['ktime']?>'>
                        <input name="gtime" class='form-control' style='width: 8em;' type="text" placeholder="结束时间" onclick="laydate()" id='gtime' value='<?=$this->get['gtime']?>'>
                    </div>
                    <div class="text-right"><input type="submit" class='btn btn-primary' placeholder="搜索"><div>
                </td>
            </tr>
        </table>
        </form>
    </div>
    <ul class="nav nav-pills">
      <li role="presentation" class="active"><a href="javascript:void(0)">优惠券列表</a></li>
      <li role="presentation"><a href="add">添加优惠券</a></li>
    </ul>
    <div style='margin-top: 1em'>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th class="col-md-2">兑换码</th>
                    <th class="col-md-2">活动名称</th>
                    <th class="col-md-2">开始时间</th>
                    <th class="col-md-2">结束时间</th>
                    <th class="col-md-1">状态</th>
                    <th class="col-md-2">创建时间</th>
                    <th class="col-md-2">操作</th>
                </tr>
            </thead>
            <tbody id="list-body">
                <?php if($this->list) { ?>
                <?php foreach($this->list as $key => $item) : ?>
                    <tr id="is_del_<?=$item['id']; ?>" <?=(time() >= $item['end_time']+86399)? 'style="background-color:#F9EDED"' :''; ?> >
                    <td class="text-center"><?= $item['coupons_number']; ?></td>
                        <td class="text-center"><?= $item['name']; ?></td>
                        <td class="text-center"><?= date('Y-m-d H:i:s', $item['start_time']); ?></td>
                        <td class="text-center"><?= date('Y-m-d H:i:s', $item['end_time']); ?></td>
                        <td class="text-center">
                            <?=(time() > $item['end_time'])?'已过期':'活动中';?>
                        </td>
                        <td class="text-center"><?= date('Y-m-d H:i:s', $item['createdTime']); ?></td>
                        <td class="text-center">
                            <ul class="list-inline">
                                <?php if (time() < $item['end_time']+86399) : ?>
                                    <li><a href="/coupons/update?id=<?= $item['id'] ?>">编辑详情</a></li>
                                    <?php if ($this->rbac == '*' ? true :(in_array('coupons_delete', $this->rbac['action']))) :?>
                                        <li class="last"><a href="javascript:void(0)" class="item-del" data-model="limittime" onclick='del(<?= $item['id'];?>)'>删除</a></li>
                                    <?php endif;?>
                                    <?php if ($this->rbac == '*' ? true :(in_array('coupons_resend', $this->rbac['action']))) :?>
                                        <li class="last"><a class="order-btn" data-toggle="modal" data-target="#myModal_<?=$item['id']?>">发放</a></li>
                                    <?php endif;?>
                                <?php else: ?>
                                    <li><a href="/coupons/update?id=<?= $item['id'] ?>">编辑详情</a></li>
                                <?php endif;?>
                            </ul>
                        </td>
                    </tr>
                    <!-- Modal -->
                    <div class="modal fade" id="myModal_<?=$item['id']?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title" id="myModalLabel">优惠券发放</h4>
                                </div>
                                <div class="modal-body">
                                    <div class="form-group" >
                                            <div class='input-group'>
                                                <div class="input-group-addon">选择发放用户</div>
                                                <select name="user_type" class="form-control" id="user_type_<?=$item['id']?>">
                                                    <option value="1">在线支付</option>
                                                    <option value="2">后支付</option>
                                                </select>
                                            </div>
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                                    <button type="button" class="btn btn-primary" onclick="if(confirm('您确定要重发优惠券吗？')==false)return false; resend(<?=$item['id']?>)" >确认发放</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Modal -->
                <?php endforeach; ?>
                <?php } ?>  
            </tbody>
        </table>
        <?= $this->paglist; ?>
    </div>
</div>
<script>
function resend(id)
{
	var user_type = $('#user_type_'+id).val();
    $.ajax({
       type: "POST",
       url: "resend",
       dataType: "json",
       data: "id="+id+'&user_type='+user_type,
       success: function(data) {
           if (data) {
        	   alert('发送成功');
           } else {
        	   alert('发送失败');
           }
       }
    });
}

$(document).on('submit','#ajaxform',function(){
    var ktime = $('#ktime').val();
    var gtime = $('#gtime').val();
    if(ktime > gtime){ alert('开始时间不能小于结束时间');return false;}
});

function del(id)
{
	if(confirm('您确定要删除该优惠券吗？') == false) {
		return false;
	} else {
        $.ajax({
            type: "POST",
            url: "delete",
            dataType: "json",
            data: "id="+id,
            success: function(data){
                if (data) {
                    $("#is_del_"+id).remove();
                    alert('删除成功');
                } else {
                	alert('请重试');
                }
            }
         });
	}
}

</script>