<script src="/laydate/laydate.js" type="text/javascript"></script>
<script src="/js/multiselect.js" type="text/javascript"></script>
<nav class="col-md-2 hidden-print dev-sidebar">
    <?php include(dirname(__FILE__) . '/../sys/dev_nav.phtml')?>
</nav>
<style>
th {text-align: center;}
</style>

<!-- 代金券详情 -->
<div class="col-md-10">
    <ol class="breadcrumb">
      <li><a href="#">优惠券管理</a></li>
      <li class="active">编辑优惠券</li>
    </ol>
    <ul class="nav nav-pills">
      <li role="presentation" class=""><a href="list">优惠券列表</a></li>
      <li role="presentation" class='active'><a href="javascript:void(0)">编辑优惠券</a></li>
    </ul>
    <br>
    <div id='errors'></div>
    <?php /*=(time() >= $this->info['end_time']+86399) ? '<fieldset disabled="">' : ''*/?>
    <form method="post" action="javascript:void(0)" id="post-form" class="form-horizontal col-sm-12">
        <div class="form-group col-sm-12">
            <label class="col-sm-2 control-label">公司<span class='s'> *</span></label>
            <div class="col-sm-4">
                <select name="cid" class='form-control' id='cid' <?=($this->rbac == '*' ? '' : 'disabled')?>>
                    <?php foreach($this->getCompanyList as $k => $v){ ?>
                        <option value="<?=$v['id']?>" <?= ($this->info['cid'] == $v['id']) ? 'selected=selected' :'' ?>><?=$v['name']; ?></option>
                    <?php } ?>
                </select>
            </div>
        </div>
        <div class="form-group col-sm-12">
            <label class="col-sm-2 control-label">线上线下<span class='s'> *</span></label>
            <div class="col-sm-4">
                <select name="status" class='form-control' id='status' <?=($this->rbac == '*' ? '' : 'disabled')?>>
                    <option value="0" <?= ($this->info['status'] == '0') ? 'selected=selected' :'' ?>>线上</option>
                    <option value="1" <?= ($this->info['status'] == '1') ? 'selected=selected' :'' ?>>线下</option>
                </select>
            </div>
        </div>
        <div class="form-group col-sm-12">
            <label class="col-sm-2 control-label">活动名称<span class='s'> *</span></label>
            <div class="col-md-4">
                <input class="form-control" type="text" name="name" value="<?= $this->info['name']; ?>" id="name">
            </div> 
        </div>
        <div class="form-group col-sm-12">
            <label class="col-sm-2 control-label">折扣<span class='s'> *</span></label>
            <div class="col-md-4" style='float:left'>
                <input type="text" class='form-control' placeholder="折扣" name="type_num" value='<?=$this->info['type_num']?>'>
            </div>
        </div>
        <div class="form-group col-sm-12">
            <label class="col-sm-2 control-label">活动时间<span class='s'> *</span></label>
            <div class="col-md-3" style='float:left'>
                <div class="input-group">
                    <div class="input-group-addon">开始</div>
                    <input type="text" class='form-control' placeholder="开始时间" onclick="laydate()" name="start_time" value='<?=date('Y-m-d', $this->info['start_time'])?>'>
                </div>
            </div>
            <div class="col-md-3" style='float:left'>
                <div class="input-group">
                    <div class="input-group-addon">结束</div>
                    <input name="end_time" class='form-control' type="text" placeholder="结束时间" onclick="laydate()" value='<?=date('Y-m-d', $this->info['end_time'])?>'>
                </div>
            </div>
        </div>
        <div class="form-group col-sm-12">
            <label class="col-sm-2 control-label">优惠券描述<span class='s'> *</span></label>
            <div class="col-md-7">
                <textarea class="form-control" rows="4" name="description"><?= $this->info['description']; ?></textarea>
            </div>
        </div>
        
        <div class="form-group col-sm-12">
            <label class="col-sm-2 control-label">商品搜索<span class='s'> *</span></label>
            <div class="col-sm-3">
                <input class="form-control search" type="text" id="goods-keyword" placeholder="商品关键词">
            </div>
            <button class="btn btn-primary" type="button" id="goods-search">搜索</button>
        </div>
        <div class="form-group col-sm-12" style='margin-left: 0px;width:120%'>
            <div class="col-xs-5" style='padding-left: 0px;padding-right: 0px;width: 45%'>
                <select id="keepRenderingSort" class="form-control" size="8" multiple="multiple">
                </select>
            </div>
            
            <div class="col-xs-1" style='padding-left: 0px;padding-right: 0px;margin-top: 3.5em;'>
                <button type="button" onclick="doMove('keepRenderingSort','keepRenderingSort_to')" class="btn btn-default btn-block"><i class="glyphicon glyphicon-chevron-right"></i></button>
                <button type="button" onclick="doMove('keepRenderingSort_to','keepRenderingSort')" class="btn btn-default btn-block"><i class="glyphicon glyphicon-chevron-left"></i></button>
            </div>
            
            <div class="col-xs-5" style='padding-left: 0px;padding-right: 0px;width: 45%'>
                <select id="keepRenderingSort_to" class="form-control" size="8" multiple="multiple">
                    <?=$this->getCouponsGoods;?>
                </select>
            </div>
        </div>
        <div class="field-box actions text-center" >
            <input type="hidden" value="<?=$this->info['id'];?>" name='id' id="id" />
            <input type="hidden" value="<?=$this->getCouponsVal;?>" name='goods_list' id="result" />
            <input type="submit" class="btn btn-primary" value="提交活动信息">
        </div>
    </form>
    <?=(time() >= $this->info['end_time']+86399) ? '</fieldset>' : ''?>
</div>

<script type="text/javascript">
function doMove(id1,id2){
    //获取两个下拉框对象
    if (id1 == 'keepRenderingSort' && id2 == 'keepRenderingSort_to') {
        var goods_leng = $('#keepRenderingSort option:selected').length;//选中数
        var goods_val = $('#keepRenderingSort option:selected').val();//选中的值
        var goods_arr = new Array();
        for(var i=0;i<goods_leng;i++){
            goods_arr[i] = $('#keepRenderingSort option:selected').eq(i).val();
        }
        var val = $("#result");
        var valArr = val.val();
        
        $('#result').val(valArr+'-'+goods_arr.join('-'));
    }
    if (id1 == 'keepRenderingSort_to' && id2 == 'keepRenderingSort') {
        var goods_leng = $('#keepRenderingSort_to option:selected').length;//选中数
        var goods_val = $('#keepRenderingSort_to option:selected').val();//选中的值
        var goods_arr = new Array();
        for(var i=0;i<goods_leng;i++){
            goods_arr[i] = $('#keepRenderingSort_to option:selected').eq(i).val();
        }
        
        var val = $("#result");
        var valArr = val.val().split('-');
        
        for (var i=0; i<valArr.length; i++) {
            var v = valArr[i];
            if ( $.inArray(v, goods_arr) != '-1') {
                valArr.splice(i,1);
                i--;
            }
        }
        $('#result').val(valArr.join('-'));
    }
    $("#"+id1+" option:selected").appendTo("#"+id2);
};

$('#cid').change(function(){
    $('#keepRenderingSort').empty();
    $('#keepRenderingSort_to').empty();
});

$('#goods-search').click(function(){
    var company = $('#cid').val();
    var id = $('#id').val();
    var keyword = $('#goods-keyword').val();
    var result = $('#result').val();
    $.ajax({
        type: "POST",
        url: "goodsSearch",
        dataType: "json",
        data: "company_id="+company+"&goodsName="+keyword+'&result='+result+'&id='+id,
        success: function(data){
            $('#keepRenderingSort').empty();
            $('#keepRenderingSort').append(data);
        }
     });
});
$(document).on('submit','#post-form',function(){
    $.ajax({
        type: "POST",
        url:'update',
        dataType: "json",
        data:$('#post-form').serialize(),// formid
        success: function(data) {
            if (data == 200) {
                alert('提交成功');
                window.location.href = 'list';
            } else {
                $('#errors').empty();
                $('#errors').append("<div class='alert alert-danger alert-dismissible' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button><strong>"+data.error+"</strong></div>");
            }
        },
        error: function(request) {
            $('#errors').empty();
            $('#errors').append("<div class='alert alert-danger alert-dismissible' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button><strong>提交失败</strong></div>");
        }
    });
});
</script>