<script src="/laydate/laydate.js" type="text/javascript"></script>
<nav class="col-md-2 hidden-print dev-sidebar">
    <?php include(dirname(__FILE__) . '/../sys/dev_nav.phtml')?>
</nav>
<style>
th {text-align: center;}
.table>tbody>tr>td>.input-group {float: left;padding: 0.2em;width:20%}
</style>

<div class="col-md-10">
    <ol class="breadcrumb">
      <li><a href="javascript:void(0)">广告管理</a></li>
      <li class="active">广告列表</li>
    </ol>
    <div>
        <form action="" method="get" id='ajaxform'>
            <input type="hidden" name="flag" value="<?php echo $this->get['flag']; ?>">
        <table class="table" style="background:#f5f5f5">
            <tr>
                <td>
                    <div class="input-group" style='width: 18em'>
                        <div class="input-group-addon">公司</div>
                        <select name="company_id" class='form-control' id='company_id'>
                            <option value="0">全部</option>
                            <?php foreach($this->getCompanyList as $k => $v){ ?>
                                    <option value="<?=$v['id']?>" <?= ($this->get['company_id'] == $v['id']) ? 'selected' :'' ?>><?= $v['name']; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                    <div class="input-group" style='width: 18em'>
                        <div class="input-group-addon">广告位置</div>
                        <select name="location" class='form-control' id='location'>
                            <option value=''>请选择</option>
                            <?php foreach($this->location as $k => $v){ ?>
                                    <option value="<?=$k?>" <?= ($this->get['location'] == $k) ? 'selected' :'' ?>><?= $v; ?></option>
                            <?php } ?>
                        </select>
                    </div>
                    <div class="text-right"><input type="submit" class='btn btn-primary' placeholder="搜索"><div>
                </td>
            </tr>
        </table>
        </form>
    </div>
    <ul class="nav nav-pills">
      <li role="presentation" class="active"><a href="list">广告列表</a></li>
        <li role="presentation" class="active"><a href="list?flag=1">过期广告列表</a></li>
      <li role="presentation"><a href="add">添加广告</a></li>
    </ul>
    <div style='margin-top: 1em'>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th class="col-md-2">广告名称</th>
                    <th class="col-md-2">banner位置</th>
                    <th class="col-md-2">排序</th>
                    <th class="col-md-2">开始时间</th>
                    <th class="col-md-2">结束时间</th>
                    <th class="col-md-2">操作</th>
                </tr>
            </thead>
            <tbody id="list-body">
                <?php if($this->list) { ?>
                <?php foreach($this->list as $key => $item) : ?>
                    <tr id="is_del_<?=$item['id']; ?>" <?=((time() >= $item['end_time']) && (!strcmp(date('Y-m-d H:i:s',$item['end_time']), date("Y-m-d H:i:s",time())) == 0))? 'style="background-color:#F9EDED"' :''; ?> >
                        <td class="text-center"><?= $item['name']; ?></td>
                        <td class="text-center"><?= $item['location']; ?></td>
                        <td class="text-center"><?= $item['sort']; ?></td>
                        <td class="text-center"><?= date('Y-m-d H:i:s', $item['start_time']); ?></td>
                        <td class="text-center"><?= date('Y-m-d H:i:s', $item['end_time']); ?></td>
                        <td class="text-center">
                            <ul class="list-inline">
                                <li><a href="/ad/update?id=<?= $item['id'] ?>">编辑</a></li>
                                <?php if ($this->rbac == '*' ? true :(in_array('ad_delete', $this->rbac['action']))) :?>
                                <li class="last"><a href="javascript:void(0)" class="item-del" data-model="limittime" onclick='del(<?= $item['id'];?>)'>删除</a></li>
                                <?php endif;?>
                            </ul>
                        </td>
                    </tr>
                <?php endforeach; ?>
                <?php } ?>
            </tbody>
        </table>
        <?= $this->paglist; ?>
    </div>
</div>
<script>
$(document).on('submit','#ajaxform',function(){
    var ktime = $('#ktime').val();
    var gtime = $('#gtime').val();
    if(ktime > gtime){ alert('开始时间不能小于结束时间');return false;}
});

function del(id)
{
	if(confirm('您确定要删除该活动吗？') == false) {
		return false;
	} else {
        $.ajax({
            type: "POST",
            url: "delete",
            dataType: "json",
            data: "id="+id,
            success: function(data){
                if (data) {
                    $("#is_del_"+id).remove();
                    alert('删除成功');
                } else {
                	alert('请重试');
                }
            }
         });
	}
}
</script>