    <div class="form-group">
        <label for="input-name">应用版本</label>
        <input type="text" name="name" class="form-control" placeholder="" value="<?=($this->info['name'])?$this->info['name']:''?>" style="width:300px">
    </div>
    <div class="form-group">
        <label for="input-name">Code</label>
        <input type="text" name="code" class="form-control" placeholder="" value="<?=($this->info['code'])?$this->info['code']:''?>" style="width:300px">
    </div>
    <div class="form-group">
        <label for="text-brief">应用简介</label>
        <textarea class="form-control" name="details" id='details' rows="3" style="width:400px"><?=($this->info['details'])?$this->info['details']:''?></textarea>
    </div>
    <div class="form-group">
        <label for="input-name">应用更新包</label>
        <input type="file" name="hash" id="hash">
    </div>
