<script src="/js/thumbnails.js" type="text/javascript"></script>
<script src="/laydate/laydate.js" type="text/javascript"></script>
<nav class="col-md-2 hidden-print dev-sidebar">
<?php include(dirname(__FILE__) . '/../sys/dev_nav.phtml')?>
<script>
	laydate.skin('danlan')
</script>
</nav>
<style>
th {text-align: center;}
#ajaxform>table>tbody>tr>td>div{float:left;width:25%}
.current{color:red;}
</style>
<div class="col-md-10">
    <ol class="breadcrumb">
      <li><a href="javascript:void(0)">订单管理</a></li>
      <li class="active">进货单列表</li>
    </ol>
    <div>
        <form action="" id="ajaxform" method="get">
        <table class="table" style="background:#f5f5f5">
            <tr>
                <td class='col-md-12' colspan='4'><?php echo $this->jiliancaidan; ?></td>
            </tr>
            <tr>
                <td colspan='2'>价格: <input type="text" placeholder="下限-价格" name="minprice" style='width:6em'> - <input type="text" placeholder="上限-价格" name="maxprice" style='width:6em'></td>
                <td colspan='2' class='col-md-8'>时间: <input type="text" placeholder="开始时间" id='ktime' onclick="laydate()" name="ktime" style='width:8em'> - <input name="gtime" type="text" placeholder="结束时间" id='gtime' onclick="laydate()" style='width:8em'></td>
            </tr>
            <tr>
                <td><input type="text" class="form-control" style="width:13em" name='order_number' placeholder="搜索订单号"></td>
                <td>
                    <select id="disabledSelect" style="width:8em" class="form-control" name='status'>
                        <option value=''>请选择</option>
                        <option value='1'>未发货</option>
                        <option value='2'>已发货</option>
                        <option value='3'>待收货</option>
                        <option value='4'>已收货</option>
                        <option value='5'>订单取消</option>
                    </select>
                </td>
                <td></td>
                <td><input type="submit" value="搜索"></td>
            </tr>
        </table>
        </form>
    </div>
    <table class="table table-hover" style="text-align: center;">
    <caption></caption>
    <thead>
        <tr>
          <th>订单号</th>
          <th>订单状态</th>
          <th>数量</th>
		  <th>总价</th>
		  <th>生成时间</th>
		  <th>配送商名</th>
          <th>操作</th>
        </tr>
    </thead>
      <tbody>
        <?php if ($this->order_list): ?>
        <?php foreach ($this->order_list as $order): ?>
        <tr id='deliverGoods_<?=$order['id']?>'>          
          <td class='col-md-2'><?=$order['order_number']?></td>
          <td class='col-md-1'><?=$order['status']?></td>
          <td class='col-md-1'><?=$order['goods_num']?></td>
          <td class='col-md-1'><?=$order['goods_amount']?></td>
          <td class='col-md-2'><?=date('Y-m-d H:i',$order['add_time'])?></td>
          <td class='col-md-1'><?=$order['consignee']?></td>
          <td class='col-md-2'>
			<a href="purchaseInfo?order_id=<?=$order['id']?>">查看</a>
			<?php if ($order['order_status'] == 1 && $order['pay_status'] == 1 && $order['shipping_status'] == 1) :?>
				<a href="javascript:void(0)" onclick="if(confirm('确定发货吗？')==false)return false;deliverGoods(<?=$order['id']?>)">发货</a>
			<?php endif; ?>
			<?php if ($order['order_status'] != 2 ) :?>
			<span data-toggle="modal" onmouseover="this.style.cursor='pointer'" style='color: #1d8acb' data-target="#myModal<?=$order['id']?>">取消订单</span>
			    <!-- Modal -->
                    <div class="modal fade" id="myModal<?=$order['id']?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                      <div class="modal-dialog" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel" name='content'>填写取消原因</h4>
                          </div>
                          <form action="/orders/cancelStock" method="post">
                              <input type='hidden' name='order_id' value='<?=$order['id']?>'>
                              <textarea class="form-control" rows="6" style="resize:none" name='content' placeholder='请输入取消进货单的原因。'></textarea>
                              <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                                <input type="submit" class="btn btn-primary" value='取消订单'>
                              </div>
                          </form>
                        </div>
                      </div>
                    </div>
                <!-- Modal -->
			<?php endif; ?>
          </td>
        </tr>
        <?php endforeach; ?>
        <?php endif; ?>
      </tbody>
    </table>
    <?php echo $this->paglist; ?>
</div>


<script>

$(document).on('submit','#ajaxform',function(){
    var ktime = $('#ktime').val();
    var gtime = $('#gtime').val();
    if(ktime > gtime){ alert('开始时间不能小于结束时间');return false;}
});

function deliverGoods(id)
{
	$.ajax({
	   type: "POST",
	   url: "deliverGoods",
	   dataType: "json",
	   data: "id="+id,
	   success: function(data){
		   if (data == 200) {
				window.location.reload();
		   } 
		   if (data == 400) {
			   alert('操作失败');
		   }
		
	   }
	});
}

function del(id,is_delete)
{
    $.ajax({
 	   type: "POST",
 	   url: "delete",
 	   dataType: "json",
 	   data: "id="+id+"&is_delete="+is_delete,
 	   success: function(data){
 		   if (data == 200) {
 			   $("#is_del_"+id).remove();
 			   $("#modal").append('<div class="col-md-3"></div><div class="col-md-6" style="margin-top: 60px"><div class="alert alert-success" role="alert"><p>删除成功</p></div></div><div class="col-md-3"></div>');
 			   setTimeout(function(){$("#modal").modal("hide")},2000);
 		   }
 		   if (data == 400) {
 			   alert('请重试');
 		   }
 	   }
 	});
}

</script>