<script src="/js/showTime.js"></script>
<nav class="col-md-2 hidden-print dev-sidebar">
    <?php include(dirname(__FILE__) . '/../sys/dev_nav.phtml')?>
</nav>
<div class="col-md-10">
    <h4>后台管理</h4>
    <hr>
    <?php if ($this->developer): ?>
		<p> 当前用户：<?= $this->developer['name']?></p>
        <p>电子邮箱：<?=$this->developer['email']?></p>
        <p>注册日期：<?=date('Y年m月d日 H时i分s秒',$this->developer['create_time'])?></p>
		
		<p>现在时间为：<span id="theClock" style="font-weight: bold; width: 300px;"></span></p>
    <?php endif; ?>
</div>

<style>
.table tbody>tr>td {padding-left:0;}
</style>

<script>
$(function(){
	showDT();
});
</script>