<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>登录</title>
	<meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<link rel="stylesheet" type="text/css" href="/vendor/css/ratchet.min.css" />
	<link rel="stylesheet" type="text/css" href="/css/app.css">
	<script type="text/javascript" src="/js/jquery-1.8.3.min.js"></script>
    <script type="text/javascript" src="/js/baidu_count.js"></script>
        <script type="text/javascript" src="/js/baidu_count.js"></script>
</head>
<style>
::-webkit-input-placeholder { /* WebKit browsers */ 
color: #FFFFFF; 
} 
:-moz-placeholder { /* Mozilla Firefox 4 to 18 */ 
color: #FFFFFF; 
} 
::-moz-placeholder { /* Mozilla Firefox 19+ */ 
color: #FFFFFF; 
} 
:-ms-input-placeholder { /* Internet Explorer 10+ */ 
color: #FFFFFF; 
} 
</style>
<body class="bg-bule">
    <div class="car-logo">
    	<span class="icon icon-shopcar"></span>
    </div>
    <div class="form-box container ">
    	<form action="./login" method="post">
    		<div class="input-box icon-username p-r mb-20">
    			<input class="c-white bg-bule b-b-2-bule " type="text"  name="user"  placeholder="输入用户名"  value="<?php if(isset($data['account'])):?><?=$data['account']?><?php endif;?>" />
    		</div>
    		<div class="input-box icon-password p-r mb-20">
    			<input class="c-white bg-bule b-b-c-2-white " type="password"  name="password"  placeholder="输入密码"  value="<?php if(isset($data['password'])):?><?=$data['password']?><?php endif;?>" />
    		</div>
    		<input type="submit" name="sub" class="btn btn-block c-bule btn-public mb-20 bg-l-bule b-n f-bold" value="登录" />
    		<a href="/login/lostpwd" class="fs-15 c-white">忘记密码</a>
    		<a href="#" onclick="oncl()" class="fs-15 c-white pull-right"><span class="icon icon-ewm"></span>扫码注册</a>
    	</form>
    </div>
   <script src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>
    <script>
        wx.config({
            debug: false,
            appId: '<?=$signPackage["appId"];?>',
            timestamp: <?=$signPackage["timestamp"];?>,
            nonceStr: '<?=$signPackage["nonceStr"];?>',
            signature: '<?=$signPackage["signature"];?>',
            jsApiList: [
                // 所有要调用的 API 都要加到这个列表中
                'scanQRCode'
            ]
        });
        function oncl() {
            wx.ready(function () {
                wx.checkJsApi({
                    jsApiList: [
                        'scanQRCode'
                    ],
                    success: function (res) {
                        //alert(JSON.stringify(res));
                    }
                });
                wx.scanQRCode({
                    needResult: 1, // 默认为0，扫描结果由微信处理，1则直接返回扫描结果，
                    scanType: ["qrCode", "barCode"], // 可以指定扫二维码还是一维码，默认二者都有
                    success: function (res) {
                        var result = res.resultStr; // 当needResult 为 1 时，扫码返回的结果
                        $.ajax({
                            type: 'post',
                            url: '/login/qrcode',
                            data: 'code=' + result,
                            dataType: 'json',
                            success: function (data) {
                                var str = JSON.stringify(data);
                                if (data.code == 1) {
                                    window.location.href = "/register/agreement?qrcode=" + data.message;
                                } else {
                                    alert('二维码信息错误');
                                }
                            }
                        });
                    }
                });

                wx.error(function (res) {
                    //alert(JSON.stringify(res));
                });
            });
        }
    </script>
</body>
