<nav class="col-md-2 hidden-print dev-sidebar">
    <?php include(dirname(__FILE__) . '/../sys/dev_nav.phtml')?>
</nav>
<style>
.current{color:#000000;}
th {text-align: center;}
</style>

<div class="col-md-10">
    <ol class="breadcrumb">
      <li><a href="JavaScript:void(0)">品类管理</a></li>
      <li class="active">品类列表</li>
    </ol>
    <div class="ctrls list-content">
        <form method="get">
            <table class="table" style="background:#f5f5f5">
                <tr>
                    <td>
                        <div class="input-group">
                            <div class="input-group-addon">品类名称</div>
                                <input type="text" class="form-control" style='width:13em' name='search_name' value='<?=$this->get['search_name']?>' placeholder="搜索品类">
                        </div>
                    </td>
                    <td><input type="submit" placeholder="搜索"></td>
                </tr>
            </table>
        </form>
    </div>
    <ul class="nav nav-pills">
      <li role="presentation" class="active"><a href="#">品类列表</a></li>
      <li role="presentation"><a href="/classify/add">添加品类</a></li>
    </ul>
    <br>
    <br>
    <div class="table-wrapper products-table section mt-20">
        <div class="row">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th class="col-xs-2">品类名称</th>
                    <th class="col-md-4">品类描述</th>
                    <th class="col-md-1">排序</th>
                    <th class="col-md-1">是否显示</th>
                    <th class="col-md-2">创建时间</th>
                    <th class="col-md-1">操作</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($this->list as $key=>$val) { ?>
                    <tr id="brand<?= $val['id']; ?>">
                        <td class='text-center'><?= $val['name']; ?></td>
                        <td class='text-center'><?= (!empty($val['describe'])?$val['describe']:'无') ?></td>
                        <td class='text-center'><?= $val['order']; ?></td>
                        <td class='text-center' id="is_show_<?=$val['id']?>" ><?=($val['is_show'] == 0)?"<span class='btn btn-default' id='state".$val['id']."' onclick='show(". $val['id'] .",1)'>显示</span>":"<span class='btn btn-default' id='state".$val['id']."' onclick='show(". $val['id'] .",0)'>不显示</span>" ?></td>
                        <td><?= date('Y-m-d H:i', $val['create_time'])?></td>
                        <td>
                            <ul class='list-inline text-center'>
                                <li><a href="/classify/update?id=<?= $val['id']; ?>">编辑</a></li>
                                <?php if ($this->rbac == '*' ? true :(in_array('classify_del', $this->rbac['action']))) :?>
                                    <li class="last"><a href='javascript:void(0)' onclick="if(confirm('确定要删除吗？')==false)return false; del(<?=$val['id']?>,1)">删除</a></li>
                                <?php endif;?>
                            </ul>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>
        <?=$this->paglist?>
    </div>
</div>

<script type="text/javascript">
function show(id,is_show)
{
	if ('<?php echo $this->rbac == '*' ? 'true' :(in_array('classify_upshow', $this->rbac['action']) ? 'true':'false')?>' == 'false') {
	    alert('权限不足');
	    return;
	}
    $.ajax({
       type: "POST",
       url: "upShow",
       dataType: "json",
       data: "id="+id+"&is_show="+is_show,
       success: function(data){
           if (data == 0) {
               $("#is_show_"+id).children('span').remove();
               $("#is_show_"+id).append("<span class='btn btn-default' onclick='show("+id+" ,1)'>显示</span>");alert('修改成功,品类不显示');
           } else if(data == 1) {
                $("#is_show_"+id).children('span').remove();
                $("#is_show_"+id).append("<span class='btn btn-default' onclick='show("+id+" ,0)'>不显示</span>");alert('修改成功,品类已显示');
           } 
           if (data == 400) {
               alert('修改失败');
           }
       }
    });
}

function del(id)
{
    $.ajax({
     type: "POST",
     url: "del",
     dataType: "json",
     data: "id="+id,
     success: function(data){
       if (data == 200) {
         $("#brand"+id).remove();
         $("#modal").append('<div class="col-md-3"></div><div class="col-md-6" style="margin-top: 60px"><div class="alert alert-success" role="alert"><p>删除成功</p></div></div><div class="col-md-3"></div>');
         setTimeout(function(){$("#modal").modal("hide")},2000);
       }
       if (data == 400) {
         alert('请重试');
       }
     }
  });
}
</script>