 <?php include(dirname(__FILE__) . '/../sys/header.phtml')?>
     <script type="text/javascript" src="/js/baidu_count.js"></script>
<header class="bar bar-nav bg-bule b-n">
    <a href="./setlist" class="icon icon-goback pull-left"></a>
    <h1 class="title c-white">更改联系人姓名</h1>
</header>
<div class="content container form-box mt-80" style="margin-top: 60px!important;">
    <form action="./setname" method="POST">
        <div class="input-box pt-20 clearfix">
            <span class="icon icon-ren"></span>
            <input class="b-n b-b-2-gray c-gray2 pull-right mb-35 pl-0 w-95" name="userName" placeholder=" 请输入联系人姓名"  type="text" value="<?=$name?>">
            <input type="submit"  name="sub" class="btn btn-block button-bule b-n btn-public mb-35 c-gray3 f-normal" vaue="提交">
        </div>
    </form>
</div>
 <?php include(dirname(__FILE__) . '/../sys/footer.phtml')?>