<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>付款-优惠券</title>
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <link rel="stylesheet" href="/vendor/bootstrap/v3/css/bs-col-sys.min.css" />
    <link rel="stylesheet" type="text/css" href="/vendor/css/ratchet.min.css" />
    <link rel="stylesheet" type="text/css" href="/css/app.css">
        <script type="text/javascript" src="/js/baidu_count.js"></script>
    <script src="/js/ratchet.min.js"></script>
</head>
<body class="bg-gray2">
<header class="bar bar-nav bg-bule b-n">
    <a  class="icon icon-goback pull-left" type="button" onclick="javascript:history.go(-1)"></a>

    <h1 class="title c-white">可用优惠券</h1>
</header>
    <?php if(isset($coupons)){?>
	   <div class="content content-box ptb-20 used-box">
	     <?php foreach($coupons as $k => $v){?>
	          <div class="afterpr clear">
	            <ul class="afterdjin pl-0">
	                 <li class="bg-white card-box">
	                        <div class="use-box">
	                        <div class="row">
	                            <div class="col-xs-8 pr-0">
	                                <div class="coupon1-cont-box" style="background:none;">
	                                    <h3 class="c-gray"><?=$v['name']?></h3>
	                                    <p class="goos_name" name="<?=$v['goods_name']?>">使用条件：<?=$v['goods_name']?></p>
	                                    <p>使用期限：<?=date("Y-m-d",$v['start_time'])?>-<?=date("Y-m-d",$v['end_time'])?></p>
	                                </div>
	                                </div>
	                                <div class="col-xs-4 pl-0">
	                                    <div class="discount">
	                                        <span style="font-size: 3.2em;"><?=substr($v['type_num'],0,1)?></span>
	                                        <span style="font-size: 1.2em;"><?=substr($v['type_num'],1)?>折</span>
	                                    </div>
	                                </div>
	                            </div>
	                        </div>
	                    </li>
	                </ul>
	                <div class="afterl">
	                    <div class="text-right check-box">
	                        <span class="icon icon-check-gray activity" id='<?=$v['id']?>'></span>
	                        <input type="hidden" name="couid" class="couid" value="" />
	                        <input type="hidden" name="c_name" class="c_name" value="<?=$v['name']?>" />
	                        <input type="hidden" name="g_name" class="g_name" value="<?=$v['goods_name']?>" />
	                        <input type="hidden" name="g_money" class="g_money" value="<?=$v['type_num']?>" />
	                        <?php foreach($v['goods_id'] as $k => $goods_id){?>
	                             <input type="hidden" name="<?=$v['id']?>" class='activity_goods_id' id="goods_<?=$k?>" value="<?=$goods_id?>" />
	                       <?php }?>
	                    </div>
	                </div>
	            </div>  
	         <?php }?>
	   <input type="button" name="sub" onclick="activinof(this)" class="btn btn-block button-bule b-n btn-public f-normal" value="提交">
	</div>
	<?php }else{?>
		<div class="content uncouple-box">
		    <p class="text-center c-gary1">
		        没有更多可用券了
		        <a class="c-orange ml-10" href="javascript:;">查看不可用优惠券&gt;&gt;</a>
		    </p>
		</div>
	<?php }?>
</body>
<script type="text/javascript" src="/vendor/js/zepto.min.js"></script>
<script type="text/javascript" src="/js/tjp.js"></script>
<script>
function couid(object){
	var couid=object.attr('id');
	//设置优惠券ID
	if(!object.hasClass('icon-check-on')){
		 object.siblings('.couid').attr('value',couid);
	}else{
		object.siblings('.couid').attr('value','');
	}
}

$(document).ready(function(){
    $(".icon-check-gray").click(function(){
    	couid($(this));
     });
})
function activinof(object){
	var vals=new Array();
	//var activity_goods_id=new Array();

	
	$('.activity').each(function(i){
	    if($(this).hasClass('icon-check-on')){
	    	var activity_id=$(this).siblings('.couid').attr('value');
	     	var name=$(this).siblings('.c_name').attr('value');
        	var goos_name=$(this).siblings('.g_name').attr('value');
        	var goods_id=$(this).siblings('.goods_id').attr('value');
        	var g_money=$(this).siblings('.g_money').attr('value');//打折数
     	    var len=$(this).siblings('.activity_goods_id').length;
     	    var activity_goods_id = "{";
     	    for(var i=0;i<len;i++){
     	    	var ac_g_id=$(this).siblings('#goods_'+i).attr('value');
     	    	var activity_goods_id = activity_goods_id+'"'+ac_g_id+'":"'+g_money+'",';
             }
      	   activity_goods_id += '}';
          var activity={'name':name,'goos_name':goos_name,'activity_id':activity_id,'activity_goods_id':activity_goods_id};
          vals.push(activity);
	    }
	});
	console.log(vals);
	$.ajax({
	    type:'post',
	    url:'/cart/setcookie',
	    dataType:'json',
	    data:{'info':vals,'type':1},
	    success:function(data){
	  	   if(data.code==1){
     		  window.location.href="/cart/billing";
        	}else{
        		 alert('选择优惠券失败');
	        }
		}
	});	  
}
</script>
</script>
</html>