<!doctype html>
<html lang="en" ng-app="myApp">
<head>
<meta charset="utf-8">
<title><?php echo mb_convert_encoding($title, "HTML-ENTITIES", "UTF-8"); ?></title>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no">
<style> 
html, body, div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code, del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var, b, u, i, center, dl, dt, dd, ol, ul, li,
fieldset, form, label, legend, table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, figcaption, figure, footer, header, hgroup, menu, nav, section, summary,
time, mark, audio, video, input  {
    margin: 0;
    padding: 0;
    border: none;
    outline: 0;
    font-size: 100%;
    font: inherit;
    vertical-align: baseline;
    -webkit-tap-highlight-color: rgba(0,0,0,0);
}

html, body, form, fieldset, p, div, h1, h2, h3, h4, h5, h6 {
    -webkit-text-size-adjust: none;
       -moz-text-size-adjust: none;
         -o-text-size-adjust: none;
}

article, aside, details, figcaption, figure, footer, header, hgroup, menu, nav, section {
    display: block;
}

body {
    font-family: arial, sans-serif;
}

div {
    -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
       -moz-tap-highlight-color: rgba(0, 0, 0, 0);
         -o-tap-highlight-color: rgba(0, 0, 0, 0);
}

ol, ul {
    list-style: none;
}

blockquote, q {
    quotes: none;
}

blockquote:before, blockquote:after, q:before, q:after {
    content: '';
    content: none;
}

ins {
    text-decoration: none;
}

del {
    text-decoration: line-through;
}

table {
    border-collapse: collapse;
    border-spacing: 0;
}

/* app css stylesheet */
body {
    font-family: \5FAE\8F6F\96C5\9ED1, sans-serif;
    font-size: 100%;
    line-height: 1.5;
    color: #5e5e5e;
    background: #fff;
    height: 100%;
}

a {
    text-decoration: none;
    color: #fff;
}

input[type=text] {
    border: 1px solid #ccc;
    background: #fff;
}

.container {
    padding: 1em;
}

.title {
    font-size: 1.3em;
    font-weight: bold;
    line-height: 1.5;
    letter-spacing: -1px;
    color: #000;
}

.info span {
    margin-right: 1em;
}

.content {
    color: #1f1f1f;
}

.content p {
    line-height: 1.6;
    margin: 1em 0;
}

.content img {
    max-width: 100%;
}

.content h2 {
    color: #808080;
}

@media only screen and (min-width: 480px) {
    .container {
        padding: 1.2em;
    }

    .title {
        font-size: 1.5em;
    }

    .info span {
        font-size: 1.2em;
    }

    .content p {
        font-size: 1.2em;
        line-height: 1.8;
    }
}
</style> 
</head>
<body>
    <div class="container">
        <h1 class="title"><?php echo mb_convert_encoding($title, "HTML-ENTITIES", "UTF-8"); ?></h1>
        <div class="info">
            <span><a href="<?php echo strip_tags($url); ?>">查看原文</a></span>
        </div>
        <div class="content" >
            <?php echo $content; ?>
        </div>
    </div>
</body>
</html>