<script src="/laydate/laydate.js" type="text/javascript"></script>
<script src="/js/multiselect.js" type="text/javascript"></script>
<nav class="col-md-2 hidden-print dev-sidebar">
    <?php include(dirname(__FILE__) . '/../sys/dev_nav.phtml')?>
</nav>
<style>
th {text-align: center;}
</style>

<!-- 代金券详情 -->
<div class="col-md-10">
    <ol class="breadcrumb">
      <li><a href="#">代金券管理</a></li>
      <li class="active">编辑代金券</li>
    </ol>
    <ul class="nav nav-pills">
      <li role="presentation" class=""><a href="list">代金券列表</a></li>
      <li role="presentation" class='active'><a href="javascript:void(0)">编辑代金券</a></li>
    </ul>
    <br>
    <div id='errors'></div>
    <?php /*=(time() >= $this->info['end_time']+86399) ? '<fieldset disabled="">' : ''*/?>
    <form method="post" action="javascript:void(0)" id="post-form" class="form-horizontal col-sm-12">
        <div class="form-group col-sm-12">
            <label class="col-sm-2 control-label">公司<span class='s'> *</span></label>
            <div class="col-sm-4">
                <select name="cid" class='form-control' id='cid' <?=($this->rbac == '*' ? '' : 'disabled')?>>
                    <?php foreach($this->getCompanyList as $k => $v){ ?>
                        <option value="<?=$v['id']?>" <?= ($this->info['cid'] == $v['id']) ? 'selected=selected' :'' ?>><?=$v['name']; ?></option>
                    <?php } ?>
                </select>
            </div>
        </div>
        <div class="form-group col-sm-12">
            <label class="col-sm-2 control-label">活动名称<span class='s'> *</span></label>
            <div class="col-md-4">
                <input class="form-control" type="text" name="name" value="<?= $this->info['name']; ?>" id="name">
            </div> 
        </div>
        <div class="form-group col-sm-12">
            <label class="col-sm-2 control-label">代金券金额<span class='s'> *</span></label>
            <div class="col-md-3">
                <div class="input-group">
                    <input type="text" class='form-control' placeholder="元" name="type_num" value='<?=$this->info['type_num']?>'>
                    <div class="input-group-addon">元</div>
                </div>
            </div>
        </div>
        <div class="form-group col-sm-12">
            <label class="col-sm-2 control-label">活动时间<span class='s'> *</span></label>
            <div class="col-md-3" style='float:left'>
                <div class="input-group">
                    <div class="input-group-addon">开始</div>
                    <input type="text" class='form-control' placeholder="开始时间" onclick="laydate()" name="start_time" value='<?=date('Y-m-d', $this->info['start_time'])?>'>
                </div>
            </div>
            <div class="col-md-3" style='float:left'>
                <div class="input-group">
                    <div class="input-group-addon">结束</div>
                    <input name="end_time" class='form-control' type="text" placeholder="结束时间" onclick="laydate()" value='<?=date('Y-m-d', $this->info['end_time'])?>'>
                </div>
            </div>
        </div>
        <div class="form-group col-sm-12">
            <label class="col-sm-2 control-label">代金券描述<span class='s'> *</span></label>
            <div class="col-md-7">
                <textarea class="form-control" rows="4" name="description"><?= $this->info['description']; ?></textarea>
            </div>
        </div>
        <div class="field-box actions text-center" >
            <input type="hidden" value="<?=$this->info['id'];?>" name='id' id="id" />
            <input type="submit" class="btn btn-primary" value="提交活动信息">
        </div>
    </form>
    <?=(time() >= $this->info['end_time']+86399) ? '</fieldset>' : ''?>
</div>

<script type="text/javascript">
$('input[name="type_num"]').change(function () {
	var type_num = $('input[name="type_num"]');
	//制保留2位小数，如：2，会在2后面补上00.即2.00 
    function changeTwoDecimal_f(x) {
        var f_x = parseFloat(x);
        if (isNaN(x)) {
            return '0.00';
        }
        var f_x = Math.floor(x * 100) / 100;
        var s_x = f_x.toString();
        var pos_decimal = s_x.indexOf('.');
        if (pos_decimal < 0) {
            pos_decimal = s_x.length;
            s_x += '.';
        }
        while (s_x.length <= pos_decimal + 2) {
            s_x += '0';
        }
        return s_x;
    }
	type_num.val(changeTwoDecimal_f(type_num.val()));
});

$(document).on('submit','#post-form',function(){
    $.ajax({
        type: "POST",
        url:'update',
        dataType: "json",
        data:$('#post-form').serialize(),// formid
        success: function(data) {
            if (data == 200) {
                alert('提交成功');
                window.location.href = 'list';
            } else {
                $('#errors').empty();
                $('#errors').append("<div class='alert alert-danger alert-dismissible' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button><strong>"+data.error+"</strong></div>");
            }
        },
        error: function(request) {
            $('#errors').empty();
            $('#errors').append("<div class='alert alert-danger alert-dismissible' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button><strong>提交失败</strong></div>");
        }
    });
});
</script>