 <?php include(dirname(__FILE__) . '/../sys/header.phtml')?>
     <script type="text/javascript" src="/js/baidu_count.js"></script>
<header class="bar bar-nav bg-bule b-n">
    <a href="./setlist" class="icon icon-goback pull-left"></a>
    <h1 class="title c-white">更改密码</h1>
</header>
<div class="content container form-box mt-80" style="margin-top: 35px!important;">
    <form action="./setpass" method="POST">
        <div class="input-box mt-25 clearfix">
            <span class="icon icon-gray-shuotou"></span>
            <input class="b-n b-b-2-gray c-gray2 pull-right pl-0 w-95" type="password" name="oldpwd"  placeholder=" 请输入旧密码"  value="">
        </div>
        <div class="input-box clearfix">
            <span class="icon icon-gray-shuotou"></span>
            <input class="b-n b-b-2-gray c-gray2 pull-right pl-0 w-95" type="password" name="newpwd" placeholder=" 请输入新密码"   value="">
        </div>
        <div class="input-box clearfix">
            <span class="icon icon-gray-shuotou"></span>
            <input class="b-n b-b-2-gray c-gray2 pull-right pl-0 w-95" type="password" name="rnewpwd" placeholder=" 请再次输入新密码"   value="">
        </div>
        <input type="submit" name="sub" class="btn btn-block button-bule b-n btn-public mt-20 f-normal" value="提交">
    </form>
</div>
<script type="text/javascript">
$(document).on('submit','.form-box',function(){
    var password = $("input[name='oldpwd' ]").val();
    if(!password){ alert('密码不能为空');return false;}
    var newpassword = $("input[name='newpwd']").val();
    if(!newpassword){ alert('请输入新密码');return false;}
    var repassword = $("input[name='rnewpwd']").val();
    if(!repassword){ alert('请再重新输入新密码');return false;}
    if(newpassword!=repassword){ alert('两次密码输入不一致');return false;}

});
</script>
 <?php include(dirname(__FILE__) . '/../sys/footer.phtml')?>